Repository 0xIntuition/intuition-ts, pull requests merged in 2024-12, with the labels that each got.

#958 ENG-4759 feat(portal): user overview
  apps/portal/app/components/list/follow.tsx
  apps/portal/app/routes/app+/profile+/$wallet+/index.tsx
  apps/portal/app/routes/app+/profile+/_index+/_layout.tsx
  apps/portal/app/routes/app+/profile+/_index+/index.tsx
Labels: feat

#950 ENG-4880 feat(portal): replace combobox search on add tags and add identities to list
  apps/portal/app/components/atom-search-combobox-extended.tsx
  apps/portal/app/components/atom-search-combobox.tsx
  apps/portal/app/components/create-claim/create-claim-form.tsx
  apps/portal/app/components/explore/ExploreSearchClaimInput.tsx
  apps/portal/app/components/explore/ExploreSearchForm/ExploreAddTags/ExploreAddTags.tsx
  apps/portal/app/components/explore/ExploreSearchForm/ExploreSearchForm.tsx
  apps/portal/app/components/identity-input.tsx
  apps/portal/app/components/identity/identity-search-combo-box-item.tsx
  apps/portal/app/components/identity/identity-search-combo-box.tsx
  apps/portal/app/components/identity/identity-selector.tsx
  apps/portal/app/components/lists/add-identities-list-form.tsx
  apps/portal/app/components/lists/add-identities-review.tsx
  apps/portal/app/components/lists/add-identities.tsx
  apps/portal/app/components/lists/add-list-existing-cta.tsx
  apps/portal/app/components/lists/list-utils.ts
  apps/portal/app/components/tags/add-tags.tsx
  apps/portal/app/components/tags/tag-utils.ts
  apps/portal/app/components/tags/tags-form.tsx
  apps/portal/app/components/tags/tags-review.tsx
  apps/portal/app/components/tags/tags-search-combobox.tsx
  apps/portal/app/lib/hooks/useInvalidItems.tsx
  apps/portal/app/routes/app+/profile+/_index+/_layout.tsx
  packages/1ui/src/components/Icon/Icon.sprites.svg
Labels: feat

#959 ENG-4886 feat(portal): handle invalidateQueries better on stake action
  apps/portal/app/lib/hooks/mutations/useStakeMutation.tsx
  apps/portal/app/routes/app+/claim+/$id+/index.tsx
Labels: feat

#962 ENG-4934 feat(graphql,template): graphql package updates from feature branch
  apps/template/app/routes/app+/playground.tsx
  packages/graphql/package.json
  packages/graphql/src/client.ts
  packages/graphql/src/fragments/account.graphql
  packages/graphql/src/fragments/atom.graphql
  packages/graphql/src/fragments/deposit.graphql
  packages/graphql/src/fragments/event.graphql
  packages/graphql/src/fragments/follow.graphql
  packages/graphql/src/fragments/position.graphql
  packages/graphql/src/fragments/redemption.graphql
  packages/graphql/src/fragments/triple.graphql
  packages/graphql/src/fragments/vault.graphql
  packages/graphql/src/generated/index.ts
  packages/graphql/src/queries/accounts.graphql
  packages/graphql/src/queries/atoms.graphql
  packages/graphql/src/queries/claims.graphql
  packages/graphql/src/queries/events.graphql
  packages/graphql/src/queries/lists.graphql
  packages/graphql/src/queries/positions.graphql
  packages/graphql/src/queries/triples.graphql
  packages/graphql/src/queries/vaults.graphql
Labels: feat

#966 ENG-0000 fix(portal): updates privy redirect logic
  apps/portal/app/.server/auth.ts
  apps/portal/app/.server/privy.ts
  apps/portal/app/routes/_index.tsx
  apps/portal/app/routes/intro+/index.tsx
Labels: fix

#964 ENG-0000 feat(repo): Setup graphql versioning & packaging
  .gitignore
  .prettierignore
  .verdaccio/config.yml
  package.json
  packages/1ui/project.json
  packages/1ui/tsconfig.json
  packages/1ui/tsconfig.typecheck.json
  packages/1ui/types.d.ts
  packages/graphql/README.md
  packages/graphql/codegen.ts
  packages/graphql/package.json
  packages/graphql/project.json
  packages/graphql/tsconfig.json
  packages/graphql/tsup.config.ts
  pnpm-lock.yaml
  tsconfig.base.json
Labels: feat

#967 ENG-0000 fix(data-populator): privy redirect logic refresh
  apps/data-populator/app/.client/privy-refresh.tsx
  apps/data-populator/app/.server/auth.ts
  apps/data-populator/app/.server/privy.ts
  apps/data-populator/app/components/loading-logo.tsx
  apps/data-populator/app/lib/services/cid.ts
  apps/data-populator/app/lib/services/image.ts
  apps/data-populator/app/lib/services/populate.ts
  apps/data-populator/app/lib/utils/csv.ts
  apps/data-populator/app/routes/_index.tsx
  apps/data-populator/app/routes/app+/playground.tsx
  apps/data-populator/app/routes/login.tsx
  apps/data-populator/app/routes/refresh.tsx
Labels: fix

#968 eng-4966-data-populator-try-new-regexp
  apps/data-populator/app/lib/utils/proofread.ts
Labels: title needs formatting

#969 ENG-4592 feat(graphql,template): add environment handling graphql and example in template
  apps/template/app/root.tsx
  packages/graphql/codegen.ts
  packages/graphql/package.json
  packages/graphql/src/client.ts
  packages/graphql/src/constants.ts
  packages/graphql/src/index.ts
Labels: feat

#971 ENG-4766 feat(graphql,portal): user profile data created
  apps/portal/app/components/list/active-positions-on-claims.tsx
  apps/portal/app/components/list/active-positions-on-identities.tsx
  apps/portal/app/components/list/identities.tsx
  apps/portal/app/components/profile/data-created-header.tsx
  apps/portal/app/routes/app+/profile+/_index+/data-created.tsx
  packages/graphql/src/fragments/position.graphql
  packages/graphql/src/generated/index.ts
  packages/graphql/src/queries/atoms.graphql
  packages/graphql/src/queries/positions.graphql
Labels: feat

#960 ENG-4942 feat(portal): convert identity read only route to use graphql
  apps/portal/app/components/list/claims.tsx
  apps/portal/app/routes/readonly+/identity+/$id+/index.tsx
  apps/portal/app/routes/readonly+/identity+/$id.tsx
Labels: feat

#961 ENG-4941 feat(portal): convert claim read only route to use graphql
  apps/portal/app/components/detail-info-card.tsx
  apps/portal/app/routes/readonly+/claim+/$id+/index.tsx
  apps/portal/app/routes/readonly+/claim+/$id.tsx
Labels: feat

#974 ENG-5006 fix(data-populator): atom existence bugs and db optimizations
  apps/data-populator/app/lib/services/attestor.ts
  apps/data-populator/app/lib/services/offchain-store.ts
  apps/data-populator/app/lib/services/populate.ts
  apps/data-populator/app/lib/services/supabase.ts
  apps/data-populator/app/routes/app+/index.tsx
Labels: fix

#972 ENG-4761 feat(portal): update user data created to graphql
  apps/portal/app/routes/app+/profile+/$wallet+/data-created.tsx
Labels: feat

#963 ENG-4944 feat(portal): convert profile read only route to use graphql
  apps/portal/app/routes/readonly+/profile+/$wallet+/data-about.tsx
  apps/portal/app/routes/readonly+/profile+/$wallet+/index.tsx
  apps/portal/app/routes/readonly+/profile+/$wallet.tsx
Labels: feat

#975 ENG-5014 feat(portal): lists overview
  apps/portal/app/components/list/list-claims.tsx
  apps/portal/app/routes/app+/explore+/_index+/lists.tsx
  package.json
  packages/graphql/src/generated/index.ts
  packages/graphql/src/queries/lists.graphql
Labels: feat

#976 ENG-5029 feat(portal): lists carousel
  apps/portal/app/components/lists/featured-lists-carousel.tsx
  apps/portal/app/lib/services/lists.ts
  apps/portal/app/routes/app+/home.tsx
  packages/graphql/src/generated/index.ts
Labels: feat

#980 ENG-4898 feat(data-populator): Fix CSV header proofreading, update app header, fix toast, add title
  apps/data-populator/app/components/header.tsx
  apps/data-populator/app/root.tsx
  apps/data-populator/app/routes/app+/index.tsx
Labels: feat, fix

#979 ENG-5015 feat(portal,graphql): lists detail
  apps/portal/app/components/detail-info-card.tsx
  apps/portal/app/components/list/tags.tsx
  apps/portal/app/components/lists/add-identities-list-form.tsx
  apps/portal/app/components/lists/add-identities-list-modal.tsx
  apps/portal/app/components/lists/add-identities.tsx
  apps/portal/app/components/save-list/save-form.tsx
  apps/portal/app/components/save-list/save-list-modal.tsx
  apps/portal/app/components/save-list/save-review.tsx
  apps/portal/app/components/tags/add-tags.tsx
  apps/portal/app/lib/state/store.ts
  apps/portal/app/lib/utils/misc.tsx
  apps/portal/app/routes/app+/identity+/$id.tsx
  apps/portal/app/routes/app+/list+/$id+/index.tsx
  apps/portal/app/routes/app+/list+/$id.tsx
  apps/portal/app/routes/app+/profile+/$wallet.tsx
  apps/portal/app/routes/app+/profile+/_index+/_layout.tsx
  apps/portal/app/routes/app+/quest+/chapter+/1-6-always_true.tsx
  apps/portal/app/routes/readonly+/identity+/$id.tsx
  apps/portal/app/routes/readonly+/list+/$id+/index.tsx
  apps/portal/app/routes/readonly+/list+/$id.tsx
  apps/portal/app/routes/readonly+/profile+/$wallet.tsx
  packages/1ui/src/components/IdentityRow/IdentityRow.tsx
  packages/graphql/src/fragments/triple.graphql
  packages/graphql/src/generated/index.ts
  packages/graphql/src/queries/lists.graphql
  packages/graphql/src/queries/triples.graphql
Labels: feat

#981 ENG-0000 fix(portal): add dehydrated state to list detail
  apps/portal/app/routes/app+/list+/$id.tsx
Labels: fix

#982 ENG-5146 fix(portal): audit fee fetching and calculations and fix
  apps/portal/app/components/follow/follow-modal.tsx
  apps/portal/app/components/save-list/save-list-modal.tsx
  apps/portal/app/components/stake/stake-actions.tsx
  apps/portal/app/components/stake/stake-form.tsx
  apps/portal/app/consts/general.ts
Labels: fix

#984 ENG-5165 feat(repo): bootstrap new app setup
  .github/pr-title-checker-config.json
  .github/pull_request_template.md
  apps/launchpad/.eslintrc.cjs
  apps/launchpad/.gitignore
  apps/launchpad/README.md
  apps/launchpad/app/components/providers.tsx
  apps/launchpad/app/entry.client.tsx
  apps/launchpad/app/entry.server.tsx
  apps/launchpad/app/lib/utils/logger.ts
  apps/launchpad/app/polyfills.ts
  apps/launchpad/app/root.tsx
  apps/launchpad/app/routes/_index.tsx
  apps/launchpad/app/routes/network.tsx
  apps/launchpad/app/styles/globals.css
  apps/launchpad/package.json
  apps/launchpad/postcss.config.js
  apps/launchpad/project.json
  apps/launchpad/public/favicon.ico
  apps/launchpad/public/fonts/Geist-Medium.otf
  apps/launchpad/public/fonts/Geist-Regular.otf
  apps/launchpad/public/fonts/Geist-SemiBold.otf
  apps/launchpad/tailwind.config.js
  apps/launchpad/tsconfig.json
  apps/launchpad/tsconfig.lib.json
  apps/launchpad/tsconfig.spec.json
  apps/launchpad/vite.config.ts
  apps/launchpad/vitest.config.ts
  apps/launchpad/vitest.setup.ts
  package.json
  pnpm-lock.yaml
Labels: feat

#985 ENG-4800 feat(graphql,portal): change pagination approach and migrate routes
  apps/data-populator/app/types/pagination.ts
  apps/portal/app/components/list/active-positions-on-claims.tsx
  apps/portal/app/components/list/active-positions-on-identities.tsx
  apps/portal/app/components/list/activity.tsx
  apps/portal/app/components/list/claims.tsx
  apps/portal/app/components/list/identities.tsx
  apps/portal/app/components/list/list-claims.tsx
  apps/portal/app/components/list/list.tsx
  apps/portal/app/components/list/positions-on-claim.tsx
  apps/portal/app/components/list/positions-on-identity.tsx
  apps/portal/app/components/pagination-component.tsx
  apps/portal/app/lib/hooks/useOffsetPagination.ts
  apps/portal/app/lib/services/positions.ts
  apps/portal/app/routes/app+/activity+/global.tsx
  apps/portal/app/routes/app+/activity+/personal.tsx
  apps/portal/app/routes/app+/claim+/$id+/index.tsx
  apps/portal/app/routes/app+/explore+/_index+/claims.tsx
  apps/portal/app/routes/app+/explore+/_index+/identities.tsx
  apps/portal/app/routes/app+/identity+/$id+/index.tsx
  apps/portal/app/routes/app+/profile+/$wallet+/connections.tsx
  apps/portal/app/routes/app+/profile+/$wallet+/data-about.tsx
  apps/portal/app/routes/app+/profile+/$wallet+/data-created.tsx
  apps/portal/app/routes/app+/profile+/$wallet+/index.tsx
  apps/portal/app/routes/app+/profile+/_index+/connections.tsx
  apps/portal/app/routes/app+/profile+/_index+/data-about.tsx
  apps/portal/app/routes/app+/profile+/_index+/data-created.tsx
  apps/portal/app/routes/app+/profile+/_index+/index.tsx
  apps/portal/app/routes/readonly+/claim+/$id+/index.tsx
  apps/portal/app/routes/readonly+/identity+/$id+/index.tsx
  apps/portal/app/routes/readonly+/profile+/$wallet+/data-about.tsx
  apps/portal/app/routes/readonly+/profile+/$wallet+/data-created.tsx
  apps/portal/app/routes/readonly+/profile+/$wallet+/index.tsx
  apps/portal/app/types/pagination.ts
  apps/template/app/types/pagination.ts
  packages/graphql/src/generated/index.ts
  packages/graphql/src/queries/triples.graphql
Labels: feat

#986 ENG-5180 feat(1ui): add network stats component to storybook
  packages/1ui/package.json
  packages/1ui/src/components/ClaimRow/ClaimRow.spec.tsx
  packages/1ui/src/components/NetworkStats/NetworkStats.mdx
  packages/1ui/src/components/NetworkStats/NetworkStats.spec.tsx
  packages/1ui/src/components/NetworkStats/NetworkStats.stories.tsx
  packages/1ui/src/components/NetworkStats/NetworkStats.tsx
  packages/1ui/src/components/NetworkStats/index.ts
  packages/1ui/src/components/index.tsx
  packages/1ui/src/styles/globals.css
  packages/1ui/src/styles/utils.ts
  packages/1ui/src/utils/number.ts
  packages/1ui/tailwind.config.ts
  pnpm-lock.yaml
Labels: feat

#987 ENG-5182 feat(1ui): add sidebar component in storybook
  packages/1ui/src/components/AppSidebar/AppSidebar.mdx
  packages/1ui/src/components/AppSidebar/AppSidebar.spec.tsx
  packages/1ui/src/components/AppSidebar/AppSidebar.stories.tsx
  packages/1ui/src/components/AppSidebar/AppSidebar.tsx
  packages/1ui/src/components/AppSidebar/index.ts
  packages/1ui/src/components/Sheet/Sheet.mdx
  packages/1ui/src/components/Sheet/Sheet.spec.tsx
  packages/1ui/src/components/Sheet/Sheet.stories.tsx
  packages/1ui/src/components/Sheet/Sheet.tsx
  packages/1ui/src/components/Sheet/index.ts
  packages/1ui/src/components/Sidebar/Sidebar.mdx
  packages/1ui/src/components/Sidebar/Sidebar.spec.tsx
  packages/1ui/src/components/Sidebar/Sidebar.stories.tsx
  packages/1ui/src/components/Sidebar/Sidebar.tsx
  packages/1ui/src/components/Sidebar/SidebarExample.tsx
  packages/1ui/src/components/Sidebar/index.ts
  packages/1ui/src/components/index.tsx
  packages/1ui/src/styles/utils.ts
Labels: feat

#988 ENG-5166 feat(launchpad,1ui): add sidebar to launchpad
  apps/launchpad/app/components/AppSidebar.tsx
  apps/launchpad/app/root.tsx
  apps/launchpad/app/routes/dashboard.tsx
  apps/launchpad/app/routes/discover.tsx
  apps/launchpad/package.json
  packages/1ui/src/components/AppSidebar/AppSidebar.mdx
  packages/1ui/src/components/AppSidebar/AppSidebar.spec.tsx
  packages/1ui/src/components/AppSidebar/AppSidebar.stories.tsx
  packages/1ui/src/components/AppSidebar/AppSidebar.tsx
  packages/1ui/src/components/AppSidebar/index.ts
  packages/1ui/src/components/PageHeader/PageHeader.mdx
  packages/1ui/src/components/PageHeader/PageHeader.spec.tsx
  packages/1ui/src/components/PageHeader/PageHeader.stories.tsx
  packages/1ui/src/components/PageHeader/PageHeader.tsx
  packages/1ui/src/components/PageHeader/index.ts
  packages/1ui/src/components/Sidebar/Sidebar.tsx
  packages/1ui/src/components/index.tsx
  packages/graphql/schema.graphql
  packages/graphql/src/generated/index.ts
  pnpm-lock.yaml
Labels: feat

#989 ENG-5169 feat(launchpad,1ui): add network stats to network route
  apps/launchpad/app/root.tsx
  apps/launchpad/app/routes/network.tsx
  packages/1ui/src/components/NetworkStats/NetworkStats.tsx
  packages/1ui/src/components/PageHeader/PageHeader.tsx
Labels: feat

#990 ENG-5171 feat(launchpad,1ui): create activity feed and add to network route
  apps/launchpad/app/components/ActivityFeed.tsx
  apps/launchpad/app/consts/general.ts
  apps/launchpad/app/routes/network.tsx
  apps/launchpad/package.json
  packages/1ui/src/components/Avatar/Avatar.tsx
  packages/1ui/src/components/IdentityTag/IdentityTag.tsx
  packages/1ui/src/components/NetworkStats/NetworkStats.spec.tsx
  packages/1ui/src/components/PageHeader/PageHeader.stories.tsx
  packages/1ui/src/components/Sidebar/Sidebar.spec.tsx
  pnpm-lock.yaml
Labels: feat

#991 ENG-5225 feat(portal,graphql): updates graphql package on feature/launchpad
  apps/portal/app/components/list/identities.tsx
  apps/portal/app/lib/utils/misc.tsx
  packages/graphql/schema.graphql
  packages/graphql/src/constants.ts
  packages/graphql/src/generated/index.ts
Labels: feat

#992 ENG-5200 feat(repo,launchpad,graphql): configure launchpad for render deployment
  apps/launchpad/Dockerfile
  apps/launchpad/app/root.tsx
  packages/graphql/src/generated/index.ts
  render.yaml
Labels: feat

#995 ENG-0000 fix(repo): removes the localhost fallback for codegen
  packages/graphql/codegen.ts
Labels: fix

#999 ENG-5228 feat(repo): scaffold preferences folder in launchpad
  apps/launchpad/app/components/FileExplorerSidebar.tsx
  apps/launchpad/app/root.tsx
  apps/launchpad/app/routes/_app+/dashboard.tsx
  apps/launchpad/app/routes/_app+/discover.tsx
  apps/launchpad/app/routes/_app+/network.tsx
  apps/launchpad/app/routes/_app.tsx
  apps/launchpad/app/routes/preferences+/_index.tsx
  apps/launchpad/app/routes/preferences+/_layout.tsx
  apps/launchpad/app/routes/preferences+/folder+/$folderId.tsx
  apps/launchpad/app/routes/preferences+/item+/$itemId.tsx
  apps/launchpad/package.json
  pnpm-lock.yaml
Labels: feat

#998 ENG-5252 feat(portal): add raw graphql query to quests route for nft points
  .github/workflows/deploy_dev.yml
  .github/workflows/deploy_production.yml
  .github/workflows/deploy_staging.yml
  apps/portal/Dockerfile
  apps/portal/app/lib/hooks/useRelicCounts.tsx
  apps/portal/app/routes/app+/profile+/$wallet.tsx
  apps/portal/app/routes/app+/profile+/_index+/_layout.tsx
  apps/portal/app/routes/app+/quest+/index.tsx
Labels: feat

#1000 ENG-5229 feat(repo): scaffold atom details in launchpad
  apps/launchpad/app/routes/preferences+/item+/$itemId.tsx
Labels: feat

#1001 ENG-5255 fix(portal): fix relic graphql points update in portal
  .github/workflows/deploy_dev.yml
  .github/workflows/deploy_production.yml
  .github/workflows/deploy_staging.yml
  apps/portal/Dockerfile
  apps/portal/app/lib/services/relic.ts
  apps/portal/app/routes/app+/profile+/$wallet.tsx
  apps/portal/app/routes/app+/profile+/_index+/_layout.tsx
  apps/portal/app/routes/app+/quest+/index.tsx
Labels: fix

#1002 ENG-5256 fix(portal): fix workflows and dockerfile
  .github/workflows/deploy_dev.yml
  .github/workflows/deploy_production.yml
  .github/workflows/deploy_staging.yml
  apps/portal/Dockerfile
Labels: fix

#1003 ENG-5259 fix(portal): fix relic point import paths
  apps/portal/app/routes/app+/profile+/$wallet.tsx
  apps/portal/app/routes/app+/profile+/_index+/_layout.tsx
  apps/portal/app/routes/app+/quest+/index.tsx
Labels: fix

#1004 ENG-5260 fix(portal): add arg to dockerfile
  apps/portal/Dockerfile
Labels: fix

#1005 ENG-5232 feat(launchpad): initial implementation of dashboard route
  apps/launchpad/app/components/ChapterProgress.tsx
  apps/launchpad/app/components/ChapterProgressBanner.tsx
  apps/launchpad/app/components/LevelProgress.tsx
  apps/launchpad/app/components/PortfolioStats.tsx
  apps/launchpad/app/components/TimeFilter.tsx
  apps/launchpad/app/routes/_app+/dashboard.tsx
  apps/launchpad/app/routes/_app+/network.tsx
  apps/launchpad/package.json
  packages/1ui/package.json
  packages/1ui/src/components/AggregatedMetrics/AggregatedMetrics.mdx
  packages/1ui/src/components/AggregatedMetrics/AggregatedMetrics.spec.tsx
  packages/1ui/src/components/AggregatedMetrics/AggregatedMetrics.stories.tsx
  packages/1ui/src/components/AggregatedMetrics/AggregatedMetrics.tsx
  packages/1ui/src/components/AggregatedMetrics/index.ts
  packages/1ui/src/components/Card/Card.mdx
  packages/1ui/src/components/Card/Card.spec.tsx
  packages/1ui/src/components/Card/Card.stories.tsx
  packages/1ui/src/components/Card/Card.tsx
  packages/1ui/src/components/Card/index.ts
  packages/1ui/src/components/NetworkStats/index.ts
  packages/1ui/src/components/Progress/Progress.mdx
  packages/1ui/src/components/Progress/Progress.spec.tsx
  packages/1ui/src/components/Progress/Progress.stories.tsx
  packages/1ui/src/components/Progress/Progress.tsx
  packages/1ui/src/components/Progress/index.ts
  packages/1ui/src/components/ProgressBar/ProgressBar.mdx
  packages/1ui/src/components/index.tsx
  pnpm-lock.yaml
Labels: feat

#1006 ENG-0000 fix(graphql): corrects the version to 0.3.0 from 0.4.0
  packages/graphql/package.json
Labels: fix

#1007 ENG-5262 feat(portal): update protocol points from legacy api to graphql
  .github/workflows/deploy_dev.yml
  .github/workflows/deploy_production.yml
  .github/workflows/deploy_staging.yml
  apps/portal/Dockerfile
  apps/portal/app/lib/services/protocol.ts
  apps/portal/app/routes/app+/profile+/$wallet.tsx
  apps/portal/app/routes/app+/profile+/_index+/_layout.tsx
  apps/portal/app/routes/app+/quest+/index.tsx
  apps/portal/app/routes/readonly+/profile+/$wallet.tsx
Labels: feat
