Repository 0xIntuition/intuition-ts, pull requests merged in 2025-04, with the labels that each got.

#1147 ENG-0000 feat(launchpad): Fix api env, add verification handling
  apps/launchpad/app/components/app-sidebar.tsx
  apps/launchpad/app/components/ecosystem-modal/survey-modal.tsx
  apps/launchpad/app/components/ecosystem-modal/topics-step.tsx
  apps/launchpad/app/components/epoch-accordion.tsx
  apps/launchpad/app/lib/graphql/client.ts
  apps/launchpad/app/lib/hooks/useEcosystemQuestionData.ts
  apps/launchpad/app/lib/providers/auth-provider.tsx
  apps/launchpad/app/lib/utils/claimr.ts
  apps/launchpad/app/lib/utils/constants.ts
  apps/launchpad/app/routes/_app+/claimr.tsx
  apps/launchpad/app/routes/_app+/quests+/ecosystems+/$epochId+/$questionId.tsx
  apps/launchpad/package.json
  apps/launchpad/vite.config.ts
  pnpm-lock.yaml
Labels: feat, fix

#1150 ENG-6405 feat(launchpad): Add ecosystem external links / references
  apps/launchpad/app/lib/utils/constants.ts
  apps/launchpad/app/routes/_app+/discover.tsx
  apps/launchpad/app/routes/_app+/quests+/ecosystems+/$epochId+/index.tsx
  apps/launchpad/app/routes/_app+/quests+/ecosystems+/index.tsx
  apps/launchpad/public/images/discover/ecosystems.png
Labels: feat

#1152 ENG-0000 feat(launchpad): merge feature/launchpad-dev into feature/launchpad
  apps/launchpad/app/consts/general.ts
Labels: feat

#1157 ENG-6542 feat(launchpad): Add arbitrum feature flag & fix IQ point earned values
  apps/launchpad/app/.server/env.ts
  apps/launchpad/app/components/app-sidebar.tsx
  apps/launchpad/app/components/dashboard-banner.tsx
  apps/launchpad/app/components/ecosystem-card.tsx
  apps/launchpad/app/components/ecosystem-question-card/question-card-wrapper.tsx
  apps/launchpad/app/components/ecosystem-question-card/question-row-wrapper.tsx
  apps/launchpad/app/components/ui/banner.tsx
  apps/launchpad/app/routes/_app+/dashboard.tsx
  apps/launchpad/app/routes/_app+/quests+/ecosystems+/$epochId+/$questionId.tsx
  apps/launchpad/app/routes/_app+/quests+/ecosystems+/$epochId+/index.tsx
  apps/launchpad/app/routes/_app+/quests+/ecosystems+/index.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/index.tsx
  apps/launchpad/app/routes/resources+/get-epochs.ts
Labels: title needs formatting

#1158 ENG-0000 fix(launchpad): Fix View Ecosystem Map responsiveness
  apps/launchpad/app/routes/_app+/quests+/ecosystems+/index.tsx
Labels: fix

#1160 ENG-6547 chore(launchpad): Update ecosystems SEO
  apps/launchpad/app/routes/_app+/quests+/ecosystems+/$epochId+/index.tsx
  apps/launchpad/app/routes/_app+/quests+/ecosystems+/index.tsx
Labels: chore

#1162 ENG-6559 fix(launchpad): Add number of users to question row
  apps/launchpad/app/components/ecosystem-question-card/question-row-wrapper.tsx
Labels: fix

#1164 ENG-6553 chore: get all points up to date
  apps/launchpad/app/components/ecosystem-question-card/question-row-wrapper.tsx
  apps/launchpad/app/components/points-card/level-progress.tsx
  apps/launchpad/app/consts/points.ts
  apps/launchpad/app/routes/resources+/get-points.ts
Labels: title needs formatting, chore
