Repository 0xIntuition/intuition-ts, pull requests merged in 2025-02, with the labels that each got.

#1091 ENG-5698 chore(portal,graphql): update relic points to use new points api
  apps/portal/app/lib/graphql/client.ts
  apps/portal/app/lib/services/points.ts
  apps/portal/app/routes/app+/profile+/_index+/_layout.tsx
  apps/portal/app/routes/app+/quest+/index.tsx
  apps/portal/package.json
  packages/graphql/codegen.ts
  packages/graphql/package.json
  packages/graphql/schema.graphql
  packages/graphql/src/generated/index.ts
  pnpm-lock.yaml
Labels: chore

#1085 ENG-5665 feat(launchpad,1ui): implement downvoting
  apps/launchpad/app/components/knowledge-graph/knowledge-graph.tsx
  apps/launchpad/app/components/onboarding-modal-old/constants.ts
  apps/launchpad/app/components/onboarding-modal-old/intro-step.tsx
  apps/launchpad/app/components/onboarding-modal-old/onboarding-modal.tsx
  apps/launchpad/app/components/onboarding-modal-old/subtopics-step.tsx
  apps/launchpad/app/components/onboarding-modal-old/summary-step.tsx
  apps/launchpad/app/components/onboarding-modal-old/topics-step.tsx
  apps/launchpad/app/components/onboarding-modal-old/types.ts
  apps/launchpad/app/components/signal-modal/signal-button.tsx
  apps/launchpad/app/components/signal-modal/signal-modal.tsx
  apps/launchpad/app/components/signal-modal/signal-step.tsx
  apps/launchpad/app/components/signal-modal/success-step.tsx
  apps/launchpad/app/components/signal-modal/types.ts
  apps/launchpad/app/components/signal/signal-actions.tsx
  apps/launchpad/app/components/signal/signal-button.tsx
  apps/launchpad/app/components/signal/signal-fee-breakdown.tsx
  apps/launchpad/app/components/signal/signal-form.tsx
  apps/launchpad/app/components/signal/signal-input.tsx
  apps/launchpad/app/components/signal/signal-modal.tsx
  apps/launchpad/app/components/signal/signal-review.tsx
  apps/launchpad/app/components/signal/signal-toast.tsx
  apps/launchpad/app/components/survey-modal/signal-step.tsx
  apps/launchpad/app/components/ui/table/columns.tsx
  apps/launchpad/app/components/ui/table/data-table.tsx
  apps/launchpad/app/lib/hooks/mutations/useCreateAtomMutation.tsx
  apps/launchpad/app/lib/hooks/mutations/useCreateTripleMutation.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/question+/$id.tsx
  packages/1ui/src/components/AggregatedMetrics/AggregatedMetrics.tsx
Labels: feat

#1093 ENG-5727 feat(launchpad,graphql): home page scaffolding
  apps/launchpad/app/components/account-button.tsx
  apps/launchpad/app/components/aggregate-iq.tsx
  apps/launchpad/app/components/app-sidebar.tsx
  apps/launchpad/app/components/chapter-progress.tsx
  apps/launchpad/app/components/earn-card.tsx
  apps/launchpad/app/components/earn-section.tsx
  apps/launchpad/app/components/layouts/app-shell.tsx
  apps/launchpad/app/routes/_app+/dashboard.tsx
  apps/launchpad/app/routes/_app+/rewards.tsx
Labels: feat

#1094 ENG-5683 feat(launchpad,1ui,graphql): update network page based on new designs
  apps/launchpad/app/components/activity-feed-portal.tsx
  apps/launchpad/app/components/activity-feed.tsx
  apps/launchpad/app/components/app-sidebar.tsx
  apps/launchpad/app/lib/utils/misc.tsx
  apps/launchpad/app/routes/_app+/network.tsx
  packages/1ui/src/components/AggregatedMetrics/AggregatedMetrics.spec.tsx
  packages/1ui/src/components/AggregatedMetrics/AggregatedMetrics.tsx
  packages/1ui/src/components/ClaimRow/ClaimRow.spec.tsx
  packages/1ui/src/components/ClaimRow/ClaimRow.tsx
  packages/1ui/src/components/Form/Form.spec.tsx
  packages/1ui/src/components/Icon/Icon.sprites.svg
  packages/1ui/src/components/Icon/Icon.types.ts
  packages/1ui/src/components/IdentityRow/IdentityRow.spec.tsx
  packages/1ui/src/components/IdentityRow/IdentityRow.tsx
  packages/1ui/src/components/Progress/Progress.tsx
  packages/1ui/src/components/Stepper/Stepper.spec.tsx
  packages/1ui/src/utils/number.spec.ts
Labels: feat

#1095 ENG-5739 feat(launchpad,1ui): support for multiple questions and progression
  apps/launchpad/app/components/activity-feed-portal.tsx
  apps/launchpad/app/components/activity-feed.tsx
  apps/launchpad/app/components/aggregate-iq.tsx
  apps/launchpad/app/components/app-sidebar.tsx
  apps/launchpad/app/components/atom-details-card.tsx
  apps/launchpad/app/components/atom-details-modal.tsx
  apps/launchpad/app/components/chapter-progress.tsx
  apps/launchpad/app/components/discover-card.tsx
  apps/launchpad/app/components/discover-section.tsx
  apps/launchpad/app/components/earn-card.tsx
  apps/launchpad/app/components/earn-section.tsx
  apps/launchpad/app/components/minigame-card-wrapper.tsx
  apps/launchpad/app/components/minigame-card.tsx
  apps/launchpad/app/components/survey-modal/reward-step.tsx
  apps/launchpad/app/components/survey-modal/signal-step.tsx
  apps/launchpad/app/components/survey-modal/survey-modal.tsx
  apps/launchpad/app/components/survey-modal/topics-step.tsx
  apps/launchpad/app/components/survey-modal/types.ts
  apps/launchpad/app/components/svg/points-graphic.tsx
  apps/launchpad/app/lib/graphql/types.ts
  apps/launchpad/app/lib/hooks/mutations/useCreateTripleMutation.tsx
  apps/launchpad/app/lib/hooks/useEpochProgress.ts
  apps/launchpad/app/lib/hooks/useGetQuestions.tsx
  apps/launchpad/app/lib/hooks/useQuestionCompletion.ts
  apps/launchpad/app/lib/hooks/useQuestionData.ts
  apps/launchpad/app/lib/hooks/useRelicPoints.ts
  apps/launchpad/app/lib/hooks/useUserRank.ts
  apps/launchpad/app/lib/services/epochs.ts
  apps/launchpad/app/lib/services/points.ts
  apps/launchpad/app/lib/services/questions.ts
  apps/launchpad/app/lib/state/store.ts
  apps/launchpad/app/lib/utils/constants.ts
  apps/launchpad/app/routes/_app+/dashboard.tsx
  apps/launchpad/app/routes/_app+/discover.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/index.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/question+/$id.tsx
  apps/launchpad/app/routes/actions+/reward-question-points.ts
  apps/launchpad/app/routes/resources+/get-current-epoch.ts
  apps/launchpad/app/routes/resources+/get-epoch-progress.ts
  apps/launchpad/app/routes/resources+/get-epoch-questions.ts
  apps/launchpad/app/routes/resources+/get-points.ts
  apps/launchpad/app/routes/resources+/get-question-completion.ts
  apps/launchpad/app/routes/resources+/get-questions.$id.ts
  apps/launchpad/app/routes/resources+/get-questions.ts
  apps/launchpad/app/routes/resources+/get-relic-points.ts
  apps/launchpad/app/routes/resources+/get-relic-points.tsx
  apps/launchpad/app/routes/resources+/get-user-rank.ts
  packages/1ui/src/components/AggregatedMetrics/AggregatedMetrics.spec.tsx
  packages/1ui/src/components/AggregatedMetrics/AggregatedMetrics.tsx
Labels: feat

#1097 ENG-5723 feat(launchpad): lore page
  apps/launchpad/app/components/app-sidebar.tsx
  apps/launchpad/app/components/chapter-progress.tsx
  apps/launchpad/app/components/lore/chapter-card.tsx
  apps/launchpad/app/components/lore/chapter-header.tsx
  apps/launchpad/app/components/lore/chapter-loading.tsx
  apps/launchpad/app/components/lore/chapter-navigation.tsx
  apps/launchpad/app/components/lore/chapter-sections/1-1-awakening.tsx
  apps/launchpad/app/components/lore/chapter-sections/1-2-decision.tsx
  apps/launchpad/app/components/lore/chapter-sections/1-3-oppressor.tsx
  apps/launchpad/app/components/lore/chapter-sections/1-4-pyramid.tsx
  apps/launchpad/app/components/lore/chapter-sections/2-1-gilded-cage.tsx
  apps/launchpad/app/components/lore/chapter-sections/2-2-what-lies-beyond.tsx
  apps/launchpad/app/components/lore/chapter-sections/2-3-the-portal.tsx
  apps/launchpad/app/components/lore/chapter-sections/2-4-the-power-of-many.tsx
  apps/launchpad/app/components/lore/chapter-sections/3-1-threshold.tsx
  apps/launchpad/app/components/lore/chapter-sections/3-2-unique-journey.tsx
  apps/launchpad/app/components/lore/chapter-sections/3-3-deeper-truth.tsx
  apps/launchpad/app/components/lore/chapter-sections/3-4-prove-yourself.tsx
  apps/launchpad/app/components/lore/chapter-sections/4-1-unspoken-truths.tsx
  apps/launchpad/app/components/lore/chapter-sections/4-2-the-shift.tsx
  apps/launchpad/app/components/lore/chapter-sections/5-1-advocating-intuition.tsx
  apps/launchpad/app/components/lore/chapter-sections/6-1-common-vision.tsx
  apps/launchpad/app/components/lore/chapter-sections/6-2-the-crossroads.tsx
  apps/launchpad/app/components/lore/chapter-sections/6-3-a-movement.tsx
  apps/launchpad/app/components/lore/chapter-sections/7-1-force-for-change.tsx
  apps/launchpad/app/components/lore/chapter-sections/7-2-the-epiphany.tsx
  apps/launchpad/app/components/lore/chapter-sections/7-3-the-transformation.tsx
  apps/launchpad/app/components/lore/chapter-sections/8-1-the-relic.tsx
  apps/launchpad/app/components/lore/chapter-sections/9-1-the-continuum.tsx
  apps/launchpad/app/components/lore/chapter-sections/section-header.tsx
  apps/launchpad/app/components/lore/chapters.ts
  apps/launchpad/app/lib/hooks/useReducedMotion.ts
  apps/launchpad/app/lib/types/lore.ts
  apps/launchpad/app/lib/utils/misc.tsx
  apps/launchpad/app/routes/_app+/lore+/$chapterId.tsx
  apps/launchpad/app/routes/_app+/lore+/index.tsx
  apps/launchpad/package.json
  apps/launchpad/public/images/lore/1-1-the-awakening.png
  apps/launchpad/public/images/lore/1-2-the-decision.png
  apps/launchpad/public/images/lore/1-3-a-subtle-opressor.png
  apps/launchpad/public/images/lore/1-4-the-pyramid.png
  apps/launchpad/public/images/lore/1-be-human.webp
  apps/launchpad/public/images/lore/2-lost-origins.webp
  apps/launchpad/public/images/lore/3-transcendence.webp
  apps/launchpad/public/images/lore/4-emergence.webp
  apps/launchpad/public/images/lore/5-rebirth.webp
  apps/launchpad/public/images/lore/6-choosing-your-path.webp
  apps/launchpad/public/images/lore/7-ascension.webp
  apps/launchpad/public/images/lore/8-the-relic.webp
  apps/launchpad/public/images/lore/9-the-continuum.webp
  pnpm-lock.yaml
Labels: feat

#1101 ENG-5814 feat(portal): adds new env var to dockerfile and ga workflows for portal
  .github/workflows/deploy_dev.yml
  .github/workflows/deploy_production.yml
  .github/workflows/deploy_staging.yml
  apps/portal/Dockerfile
Labels: feat

#1102 ENG-5821 feat(launchpad): prefill atom name from search term
  apps/launchpad/app/components/survey-modal/create-step.tsx
  apps/launchpad/app/components/survey-modal/survey-modal.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/$epochId+/$questionId.tsx
Labels: feat

#1103 ENG-5826 fix(launchpad,1ui): minor and non-critical QA fixes and changes
  apps/launchpad/app/components/activity-feed-portal.tsx
  apps/launchpad/app/components/app-sidebar.tsx
  apps/launchpad/app/components/survey-modal/topics-step.tsx
  apps/launchpad/app/routes/_app+/dashboard.tsx
  packages/1ui/src/components/Claim/Claim.tsx
  packages/1ui/src/components/StepIndicator/StepIndicator.tsx
Labels: fix

#1104 ENG-5829 feat(1ui): updates 1ui components with use client where needed
  packages/1ui/src/components/Button/Button.tsx
  packages/1ui/src/components/Claim/Claim.tsx
  packages/1ui/src/components/Copy/Copy.tsx
  packages/1ui/src/components/Icon/Icon.tsx
Labels: feat

#1105 ENG-5844 fix(launchpad,graphql): qa fixes, pagination on results
  apps/launchpad/app/components/app-sidebar.tsx
  apps/launchpad/app/components/layouts/app-shell-context.tsx
  apps/launchpad/app/components/lore/chapter-header.tsx
  apps/launchpad/app/components/lore/chapter-navigation.tsx
  apps/launchpad/app/components/ui/table/data-table-pagination.tsx
  apps/launchpad/app/components/ui/table/data-table.tsx
  apps/launchpad/app/routes/_app+/lore+/$chapterId.tsx
  apps/launchpad/app/routes/_app+/lore+/index.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/$epochId+/$questionId.tsx
  packages/graphql/src/generated/index.ts
  packages/graphql/src/queries/lists.graphql
Labels: fix

#1106 ENG-5861 fix(launchpad,graphql,1ui): qa fixes and improvements
  apps/launchpad/app/components/activity-feed-portal.tsx
  apps/launchpad/app/components/aggregate-iq.tsx
  apps/launchpad/app/components/app-sidebar.tsx
  apps/launchpad/app/components/auth-cover.tsx
  apps/launchpad/app/components/chapter-progress.tsx
  apps/launchpad/app/components/discover-card.tsx
  apps/launchpad/app/components/discover-section.tsx
  apps/launchpad/app/components/earn-card.tsx
  apps/launchpad/app/components/epoch-accordion.tsx
  apps/launchpad/app/components/layouts/app-shell.tsx
  apps/launchpad/app/components/page-header.tsx
  apps/launchpad/app/components/quest-row.tsx
  apps/launchpad/app/components/question-row-wrapper.tsx
  apps/launchpad/app/components/share-modal.tsx
  apps/launchpad/app/components/ui/table/data-table.tsx
  apps/launchpad/app/components/video-background.tsx
  apps/launchpad/app/lib/state/store.ts
  apps/launchpad/app/root.tsx
  apps/launchpad/app/routes/_app+/dashboard.tsx
  apps/launchpad/app/routes/_app+/discover.tsx
  apps/launchpad/app/routes/_app+/lore+/index.tsx
  apps/launchpad/app/routes/_app+/network.tsx
  apps/launchpad/app/routes/_app+/quests+/index.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/$epochId+/$questionId.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/$epochId+/index.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/index.tsx
  apps/launchpad/app/routes/_app+/rewards.tsx
  apps/launchpad/public/background-fallback.png
  apps/launchpad/public/background.webm
  packages/1ui/src/components/AggregatedMetrics/AggregatedMetrics.tsx
  packages/1ui/src/components/Sidebar/Sidebar.tsx
  packages/graphql/schema.graphql
  packages/graphql/src/generated/index.ts
Labels: fix

#1107 ENG-0000 fix(launchpad): fix build error
  apps/launchpad/app/components/share-modal.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/$epochId+/$questionId.tsx
  apps/launchpad/app/types/list-details.ts
Labels: fix

#1108 ENG-5734 feat(launchpad): rewards page design enhancements and updates
  apps/launchpad/app/components/level-indicator.tsx
  apps/launchpad/app/components/lore/chapter-sections/1-1-awakening.tsx
  apps/launchpad/app/components/lore/chapter-sections/1-2-decision.tsx
  apps/launchpad/app/components/lore/chapter-sections/1-3-oppressor.tsx
  apps/launchpad/app/components/lore/chapter-sections/1-4-pyramid.tsx
  apps/launchpad/app/components/mastery-card.tsx
  apps/launchpad/app/components/mastery-preview.tsx
  apps/launchpad/app/components/points-card/acts-progress.tsx
  apps/launchpad/app/components/points-card/level-progress.tsx
  apps/launchpad/app/components/points-card/points-card.tsx
  apps/launchpad/app/components/quest-card.tsx
  apps/launchpad/app/components/quest-row.tsx
  apps/launchpad/app/components/svg/level-indicator-graphic.tsx
  apps/launchpad/app/components/svg/points-graphic.tsx
  apps/launchpad/app/consts/levels.ts
  apps/launchpad/app/consts/points.ts
  apps/launchpad/app/lib/utils/misc.tsx
  apps/launchpad/app/routes/_app+/rewards.tsx
  apps/launchpad/public/images/lore/1-1-the-awakening.png
  apps/launchpad/public/images/lore/1-1-the-awakening.webp
  apps/launchpad/public/images/lore/1-2-the-decision.png
  apps/launchpad/public/images/lore/1-2-the-decision.webp
  apps/launchpad/public/images/lore/1-3-a-subtle-opressor.png
  apps/launchpad/public/images/lore/1-3-a-subtle-opressor.webp
  apps/launchpad/public/images/lore/1-4-the-pyramid.png
  apps/launchpad/public/images/lore/1-4-the-pyramid.webp
  apps/launchpad/public/images/lore/2-1.webp
  apps/launchpad/public/images/lore/2-2.webp
  apps/launchpad/public/images/lore/2-3.webp
  apps/launchpad/public/images/lore/3-1.webp
  apps/launchpad/public/images/lore/4-1.webp
  apps/launchpad/public/images/lore/6-1.webp
  apps/launchpad/public/images/lore/7-1.webp
Labels: feat

#1111 ENG-5900 fix(launchpad,1ui): qa fixes and enhancements
  apps/launchpad/app/.server/api.ts
  apps/launchpad/app/.server/auth.ts
  apps/launchpad/app/components/account-button.tsx
  apps/launchpad/app/components/activity-feed-portal.tsx
  apps/launchpad/app/components/aggregate-iq.tsx
  apps/launchpad/app/components/app-sidebar.tsx
  apps/launchpad/app/components/auth-cover.tsx
  apps/launchpad/app/components/chapter-progress.tsx
  apps/launchpad/app/components/discover-card.tsx
  apps/launchpad/app/components/earn-card.tsx
  apps/launchpad/app/components/earn-section.tsx
  apps/launchpad/app/components/epoch-accordion.tsx
  apps/launchpad/app/components/epoch-status.tsx
  apps/launchpad/app/components/layouts/app-shell.tsx
  apps/launchpad/app/components/level-indicator.tsx
  apps/launchpad/app/components/loading-state.tsx
  apps/launchpad/app/components/lore/chapter-navigation.tsx
  apps/launchpad/app/components/mastery-card.tsx
  apps/launchpad/app/components/mastery-preview.tsx
  apps/launchpad/app/components/points-card/acts-progress.tsx
  apps/launchpad/app/components/quest-row.tsx
  apps/launchpad/app/components/question-card-wrapper.tsx
  apps/launchpad/app/components/question-card.tsx
  apps/launchpad/app/components/question-row-wrapper.tsx
  apps/launchpad/app/components/question-row.tsx
  apps/launchpad/app/components/signal-modal/signal-step.tsx
  apps/launchpad/app/components/ui/table/columns.tsx
  apps/launchpad/app/components/ui/table/data-table-column-header.tsx
  apps/launchpad/app/components/ui/table/data-table.tsx
  apps/launchpad/app/lib/hooks/useQuestionData.ts
  apps/launchpad/app/lib/hooks/useSearchAndSortParams.tsx
  apps/launchpad/app/lib/hooks/useTotalCompletedQuestions.ts
  apps/launchpad/app/lib/providers/auth-provider.tsx
  apps/launchpad/app/lib/providers/privy.tsx
  apps/launchpad/app/lib/services/epochs.ts
  apps/launchpad/app/lib/services/questions.ts
  apps/launchpad/app/root.tsx
  apps/launchpad/app/routes/_app+/dashboard.tsx
  apps/launchpad/app/routes/_app+/network.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/$epochId+/$questionId.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/index.tsx
  apps/launchpad/app/routes/_app+/rewards.tsx
  apps/launchpad/app/routes/resources+/get-questions.$id.ts
  apps/launchpad/app/routes/resources+/get-total-completed-questions.ts
  apps/launchpad/package.json
  apps/launchpad/tailwind.config.js
  packages/1ui/src/components/AggregatedMetrics/AggregatedMetrics.tsx
  pnpm-lock.yaml
Labels: fix

#1113 ENG-5911 fix(launchpad): qa and enhancements (smoke test checkpoint)
  apps/launchpad/app/components/chapter-progress.tsx
  apps/launchpad/app/components/lore/chapter-card.tsx
  apps/launchpad/app/components/ui/table/data-table.tsx
  apps/launchpad/app/lib/consts/chapters.ts
  apps/launchpad/app/lib/services/epochs.ts
  apps/launchpad/app/lib/services/points.ts
  apps/launchpad/app/lib/services/questions.ts
  apps/launchpad/app/routes/_app+/dashboard.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/$epochId+/$questionId.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/$epochId+/index.tsx
  apps/launchpad/app/routes/resources+/get-epoch.ts
  apps/launchpad/app/routes/resources+/get-question-completion.ts
  apps/launchpad/app/styles/globals.css
Labels: fix

#1114 ENG-5928 fix(launchpad,graphql): qa fixes and enhancements from smoke test
  apps/launchpad/app/components/app-sidebar.tsx
  apps/launchpad/app/components/atom-details-card.tsx
  apps/launchpad/app/components/atom-details-modal.tsx
  apps/launchpad/app/components/chapter-progress.tsx
  apps/launchpad/app/components/earn-card.tsx
  apps/launchpad/app/components/knowledge-graph/knowledge-graph.tsx
  apps/launchpad/app/components/mastery-card.tsx
  apps/launchpad/app/components/mastery-preview.tsx
  apps/launchpad/app/components/question-card.tsx
  apps/launchpad/app/components/question-row.tsx
  apps/launchpad/app/components/survey-modal/reward-step.tsx
  apps/launchpad/app/components/survey-modal/survey-modal.tsx
  apps/launchpad/app/components/survey-modal/topics-step.tsx
  apps/launchpad/app/components/survey-modal/types.ts
  apps/launchpad/app/consts/chapters.ts
  apps/launchpad/app/consts/general.ts
  apps/launchpad/app/consts/index.ts
  apps/launchpad/app/consts/points.ts
  apps/launchpad/app/lib/providers/auth-provider.tsx
  apps/launchpad/app/lib/providers/privy.tsx
  apps/launchpad/app/lib/services/points.ts
  apps/launchpad/app/lib/utils/privy-errors.ts
  apps/launchpad/app/routes/_app+/dashboard.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/$epochId+/$questionId.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/$epochId+/index.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/index.tsx
  apps/launchpad/app/routes/resources+/get-questions.ts
  apps/launchpad/package.json
  apps/launchpad/vite.config.ts
  packages/graphql/src/generated/index.ts
  packages/graphql/src/queries/accounts.graphql
  packages/graphql/src/queries/lists.graphql
  pnpm-lock.yaml
Labels: fix

#1115 ENG-0000 feat(launchpad): merge feature/launchpad-dev into feature/launchpad
  apps/launchpad/app/components/app-sidebar.tsx
  apps/launchpad/app/components/atom-details-card.tsx
  apps/launchpad/app/components/atom-details-modal.tsx
  apps/launchpad/app/components/chapter-progress.tsx
  apps/launchpad/app/components/earn-card.tsx
  apps/launchpad/app/components/knowledge-graph/knowledge-graph.tsx
  apps/launchpad/app/components/mastery-card.tsx
  apps/launchpad/app/components/mastery-preview.tsx
  apps/launchpad/app/components/question-card.tsx
  apps/launchpad/app/components/question-row.tsx
  apps/launchpad/app/components/survey-modal/reward-step.tsx
  apps/launchpad/app/components/survey-modal/survey-modal.tsx
  apps/launchpad/app/components/survey-modal/topics-step.tsx
  apps/launchpad/app/components/survey-modal/types.ts
  apps/launchpad/app/consts/chapters.ts
  apps/launchpad/app/consts/general.ts
  apps/launchpad/app/consts/index.ts
  apps/launchpad/app/consts/points.ts
  apps/launchpad/app/lib/providers/auth-provider.tsx
  apps/launchpad/app/lib/providers/privy.tsx
  apps/launchpad/app/lib/services/points.ts
  apps/launchpad/app/lib/utils/privy-errors.ts
  apps/launchpad/app/routes/_app+/dashboard.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/$epochId+/$questionId.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/$epochId+/index.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/index.tsx
  apps/launchpad/app/routes/resources+/get-questions.ts
  apps/launchpad/package.json
  apps/launchpad/vite.config.ts
  packages/graphql/src/generated/index.ts
  packages/graphql/src/queries/accounts.graphql
  packages/graphql/src/queries/lists.graphql
  pnpm-lock.yaml
Labels: feat

#1116 ENG-5952 fix(launchpad): qa and enhancements 2-19-25 smoke test
  apps/launchpad/app/components/activity-feed-portal.tsx
  apps/launchpad/app/components/discover-card.tsx
  apps/launchpad/app/components/discover-section.tsx
  apps/launchpad/app/components/share-modal.tsx
  apps/launchpad/app/components/social-links.tsx
  apps/launchpad/app/components/survey-modal/reward-step.tsx
  apps/launchpad/app/components/survey-modal/survey-modal.tsx
  apps/launchpad/app/components/survey-modal/topics-step.tsx
  apps/launchpad/app/routes/_app+/discover.tsx
  apps/launchpad/app/routes/_app+/network.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/$epochId+/$questionId.tsx
  apps/launchpad/public/images/discover/chrome-extension.png
  apps/launchpad/public/images/discover/collections.webp
  apps/launchpad/public/images/discover/data-populator.png
  apps/launchpad/public/images/discover/documentation.webp
  apps/launchpad/public/images/discover/litepaper.webp
  apps/launchpad/public/images/discover/metamask-snap.png
  apps/launchpad/public/images/discover/portal.png
  apps/launchpad/public/images/discover/raycast.webp
  apps/launchpad/public/images/discover/repustation.webp
  apps/launchpad/public/images/discover/slack-bot.webp
  apps/launchpad/public/images/discover/social/discord.webp
  apps/launchpad/public/images/discover/social/github.webp
  apps/launchpad/public/images/discover/social/guild.webp
  apps/launchpad/public/images/discover/social/linkedin.webp
  apps/launchpad/public/images/discover/social/medium.webp
  apps/launchpad/public/images/discover/social/mirror.webp
  apps/launchpad/public/images/discover/social/telegram.webp
  apps/launchpad/public/images/discover/social/twitter.webp
  apps/launchpad/public/images/discover/social/warpcast.webp
  apps/launchpad/public/images/discover/spoc-2.webp
  apps/launchpad/public/images/discover/spoc.png
  apps/launchpad/public/images/discover/valuesys.png
  apps/launchpad/public/images/discover/whitepaper.webp
Labels: fix

#1117 ENG-0000 feat(launchpad): merge feature/launchpad-dev into feature/launchpad
  apps/launchpad/app/components/activity-feed-portal.tsx
  apps/launchpad/app/components/discover-card.tsx
  apps/launchpad/app/components/discover-section.tsx
  apps/launchpad/app/components/share-modal.tsx
  apps/launchpad/app/components/social-links.tsx
  apps/launchpad/app/components/survey-modal/reward-step.tsx
  apps/launchpad/app/components/survey-modal/survey-modal.tsx
  apps/launchpad/app/components/survey-modal/topics-step.tsx
  apps/launchpad/app/routes/_app+/discover.tsx
  apps/launchpad/app/routes/_app+/network.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/$epochId+/$questionId.tsx
  apps/launchpad/public/images/discover/chrome-extension.png
  apps/launchpad/public/images/discover/collections.webp
  apps/launchpad/public/images/discover/data-populator.png
  apps/launchpad/public/images/discover/documentation.webp
  apps/launchpad/public/images/discover/litepaper.webp
  apps/launchpad/public/images/discover/metamask-snap.png
  apps/launchpad/public/images/discover/portal.png
  apps/launchpad/public/images/discover/raycast.webp
  apps/launchpad/public/images/discover/repustation.webp
  apps/launchpad/public/images/discover/slack-bot.webp
  apps/launchpad/public/images/discover/social/discord.webp
  apps/launchpad/public/images/discover/social/github.webp
  apps/launchpad/public/images/discover/social/guild.webp
  apps/launchpad/public/images/discover/social/linkedin.webp
  apps/launchpad/public/images/discover/social/medium.webp
  apps/launchpad/public/images/discover/social/mirror.webp
  apps/launchpad/public/images/discover/social/telegram.webp
  apps/launchpad/public/images/discover/social/twitter.webp
  apps/launchpad/public/images/discover/social/warpcast.webp
  apps/launchpad/public/images/discover/spoc-2.webp
  apps/launchpad/public/images/discover/spoc.png
  apps/launchpad/public/images/discover/valuesys.png
  apps/launchpad/public/images/discover/whitepaper.webp
Labels: feat

#1120 ENG-0000 feat(launchpad): merge feature/launchpad-dev into feature/launchpad
  apps/launchpad/app/components/atom-details-modal.tsx
  apps/launchpad/app/components/discover-card.tsx
  apps/launchpad/app/components/earn-card.tsx
  apps/launchpad/app/components/signal-modal/signal-modal.tsx
  apps/launchpad/app/components/ui/table/columns.tsx
  apps/launchpad/app/root.tsx
  apps/launchpad/app/routes/_app+/discover.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/$epochId+/$questionId.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/$epochId+/index.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/index.tsx
  apps/launchpad/public/images/discover/collections.webp
  apps/launchpad/public/images/discover/documentation.webp
  apps/launchpad/public/images/discover/extension.webp
  apps/launchpad/public/images/discover/intuition.webp
  apps/launchpad/public/images/discover/litepaper.webp
  apps/launchpad/public/images/discover/metamask.webp
  apps/launchpad/public/images/discover/portal.webp
  apps/launchpad/public/images/discover/repustation.webp
  apps/launchpad/public/images/discover/slack-bot.webp
  apps/launchpad/public/images/discover/spoc.webp
  apps/launchpad/public/images/discover/upload.webp
  apps/launchpad/public/images/discover/whitepaper.webp
Labels: feat

#1121 ENG-5971 fix(launchpad,1ui): post launch fixes and enhancements
  apps/launchpad/app/.client/privy-logout.tsx
  apps/launchpad/app/.client/wallet-sync.tsx
  apps/launchpad/app/components/aggregate-iq.tsx
  apps/launchpad/app/components/app-sidebar.tsx
  apps/launchpad/app/components/atom-details-card.tsx
  apps/launchpad/app/components/atom-details-modal.tsx
  apps/launchpad/app/components/chapter-progress.tsx
  apps/launchpad/app/components/epoch-accordion.tsx
  apps/launchpad/app/components/layouts/app-shell.tsx
  apps/launchpad/app/components/loading-logo.tsx
  apps/launchpad/app/components/lore/chapter-card.tsx
  apps/launchpad/app/components/lore/chapter-navigation.tsx
  apps/launchpad/app/components/mastery-preview.tsx
  apps/launchpad/app/components/page-header.tsx
  apps/launchpad/app/components/quest-row.tsx
  apps/launchpad/app/components/question-card.tsx
  apps/launchpad/app/components/signal-modal/signal-modal.tsx
  apps/launchpad/app/components/signal-modal/signal-step.tsx
  apps/launchpad/app/components/survey-modal/signal-step.tsx
  apps/launchpad/app/components/survey-modal/survey-modal.tsx
  apps/launchpad/app/components/survey-modal/topics-step.tsx
  apps/launchpad/app/components/ui/table/columns.tsx
  apps/launchpad/app/components/ui/table/data-table-column-header.tsx
  apps/launchpad/app/components/ui/table/data-table.tsx
  apps/launchpad/app/lib/hooks/useMediaQuery.ts
  apps/launchpad/app/lib/utils/constants.ts
  apps/launchpad/app/routes/_app+/dashboard.tsx
  apps/launchpad/app/routes/_app+/lore+/index.tsx
  apps/launchpad/app/routes/_app+/network.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/$epochId+/$questionId.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/$epochId+/index.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/index.tsx
  apps/launchpad/app/routes/_app.tsx
  apps/launchpad/app/styles/embla.css
  packages/1ui/src/components/Sidebar/Sidebar.tsx
  packages/1ui/src/components/StepIndicator/Step.tsx
  packages/1ui/src/components/StepIndicator/StepIndicator.tsx
Labels: fix

#1122 ENG-5976 fix(launchpad): bugfixes and enhancements
  apps/launchpad/app/components/quest-row.tsx
  apps/launchpad/app/components/question-card-wrapper.tsx
  apps/launchpad/app/components/survey-modal/reward-step.tsx
  apps/launchpad/app/components/survey-modal/survey-modal.tsx
  apps/launchpad/app/components/survey-modal/topics-step.tsx
  apps/launchpad/app/routes/_app+/lore+/index.tsx
  apps/launchpad/app/routes/_app+/quests+/index.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/index.tsx
  apps/launchpad/app/routes/actions+/reward-question-points.ts
Labels: fix

#1123 ENG-0000 feat(launchpad): merge feature/launchpad-dev into feature/launchpad
  apps/launchpad/app/.client/privy-logout.tsx
  apps/launchpad/app/.client/wallet-sync.tsx
  apps/launchpad/app/components/aggregate-iq.tsx
  apps/launchpad/app/components/app-sidebar.tsx
  apps/launchpad/app/components/atom-details-card.tsx
  apps/launchpad/app/components/atom-details-modal.tsx
  apps/launchpad/app/components/chapter-progress.tsx
  apps/launchpad/app/components/epoch-accordion.tsx
  apps/launchpad/app/components/layouts/app-shell.tsx
  apps/launchpad/app/components/loading-logo.tsx
  apps/launchpad/app/components/lore/chapter-card.tsx
  apps/launchpad/app/components/lore/chapter-navigation.tsx
  apps/launchpad/app/components/mastery-preview.tsx
  apps/launchpad/app/components/page-header.tsx
  apps/launchpad/app/components/quest-row.tsx
  apps/launchpad/app/components/question-card-wrapper.tsx
  apps/launchpad/app/components/question-card.tsx
  apps/launchpad/app/components/signal-modal/signal-modal.tsx
  apps/launchpad/app/components/signal-modal/signal-step.tsx
  apps/launchpad/app/components/survey-modal/reward-step.tsx
  apps/launchpad/app/components/survey-modal/signal-step.tsx
  apps/launchpad/app/components/survey-modal/survey-modal.tsx
  apps/launchpad/app/components/survey-modal/topics-step.tsx
  apps/launchpad/app/components/ui/table/columns.tsx
  apps/launchpad/app/components/ui/table/data-table-column-header.tsx
  apps/launchpad/app/components/ui/table/data-table.tsx
  apps/launchpad/app/lib/consts/chapters.ts
  apps/launchpad/app/lib/hooks/useMediaQuery.ts
  apps/launchpad/app/lib/providers/auth-provider.tsx
  apps/launchpad/app/lib/utils/constants.ts
  apps/launchpad/app/routes/_app+/dashboard.tsx
  apps/launchpad/app/routes/_app+/discover.tsx
  apps/launchpad/app/routes/_app+/lore+/index.tsx
  apps/launchpad/app/routes/_app+/network.tsx
  apps/launchpad/app/routes/_app+/quests+/index.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/$epochId+/$questionId.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/$epochId+/index.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/index.tsx
  apps/launchpad/app/routes/_app.tsx
  apps/launchpad/app/routes/actions+/reward-question-points.ts
  apps/launchpad/app/styles/embla.css
  packages/1ui/src/components/Sidebar/Sidebar.tsx
  packages/1ui/src/components/StepIndicator/Step.tsx
  packages/1ui/src/components/StepIndicator/StepIndicator.tsx
  pnpm-lock.yaml
Labels: feat

#1124 ENG-5977 feat(portal): disable portal quests
  apps/portal/app/.server/quest.ts
  apps/portal/app/components/quest/activities/stake-claim-activity.tsx
  apps/portal/app/components/quest/detail/layout.tsx
  apps/portal/app/components/quest/quest-card-button.tsx
  apps/portal/app/components/quest/quest-card.tsx
  apps/portal/app/components/quest/quest-criteria-card.tsx
  apps/portal/app/components/quest/quest-points-display.tsx
  apps/portal/app/components/quest/quest-set-progress-card.tsx
  apps/portal/app/components/quest/quest-status-card.tsx
  apps/portal/app/components/quest/quest-status-indicator.tsx
  apps/portal/app/consts/quest.ts
  apps/portal/app/lib/hooks/useQuestCompletion.tsx
  apps/portal/app/routes/app+/quest+/chapter+/$id.tsx
  apps/portal/app/routes/app+/quest+/chapter+/1-1-create_atom.tsx
  apps/portal/app/routes/app+/quest+/chapter+/1-2-stake_identity.tsx
  apps/portal/app/routes/app+/quest+/chapter+/1-3-create_claim.tsx
  apps/portal/app/routes/app+/quest+/chapter+/1-4-stake_claim.tsx
  apps/portal/app/routes/app+/quest+/chapter+/1-5-counter_stake_claim.tsx
  apps/portal/app/routes/app+/quest+/chapter+/1-6-always_true.tsx
  apps/portal/app/routes/app+/quest+/chapter+/1-7-test_atom.tsx
  apps/portal/app/routes/app+/quest+/index.tsx
  apps/portal/app/routes/app+/quest+/narrative+/$id.tsx
Labels: chore

#1125 ENG-5978 fix(launchpad): fix privy
  apps/launchpad/app/.client/wallet-sync.tsx
  apps/launchpad/app/components/account-button.tsx
  apps/launchpad/app/components/app-sidebar.tsx
  apps/launchpad/app/components/submit-button.tsx
  apps/launchpad/app/components/survey-modal/reward-step.tsx
  apps/launchpad/app/components/survey-modal/survey-modal.tsx
  apps/launchpad/app/consts/general.ts
  apps/launchpad/app/lib/hooks/usePrivyContract.ts
  apps/launchpad/app/lib/hooks/usePrivyWallet.ts
  apps/launchpad/app/lib/providers/auth-provider.tsx
  apps/launchpad/app/lib/utils/privy-errors.ts
  apps/launchpad/app/routes/_app.tsx
Labels: fix

#1127 ENG-0000 fix(launchpad): fix merge issues
  apps/launchpad/app/.client/wallet-sync.tsx
  apps/launchpad/app/components/survey-modal/reward-step.tsx
  apps/launchpad/app/components/survey-modal/survey-modal.tsx
  apps/launchpad/app/lib/providers/auth-provider.tsx
Labels: fix

#1126 ENG-0000 feat(launchpad): merge feature/launchpad-dev into feature/launchpad
  apps/launchpad/app/.client/wallet-sync.tsx
  apps/launchpad/app/components/account-button.tsx
  apps/launchpad/app/components/app-sidebar.tsx
  apps/launchpad/app/components/submit-button.tsx
  apps/launchpad/app/components/survey-modal/reward-step.tsx
  apps/launchpad/app/components/survey-modal/survey-modal.tsx
  apps/launchpad/app/consts/general.ts
  apps/launchpad/app/lib/hooks/usePrivyContract.ts
  apps/launchpad/app/lib/hooks/usePrivyWallet.ts
  apps/launchpad/app/lib/providers/auth-provider.tsx
  apps/launchpad/app/lib/utils/privy-errors.ts
  apps/launchpad/app/routes/_app.tsx
Labels: feat

#1129 ENG-0000 feat(launchpad): merge feature/launchpad-dev into feature/launchpad
  apps/launchpad/app/routes/_app+/quests+/questions+/$epochId+/$questionId.tsx
Labels: feat
