Repository 0xIntuition/intuition-ts, pull requests merged in 2025-01, with the labels that each got.

#1010 ENG-5227 feat(launchpad): scaffold preferences onboarding modal
  apps/launchpad/app/components/OnboardingModal/IntroStep.tsx
  apps/launchpad/app/components/OnboardingModal/OnboardingModal.tsx
  apps/launchpad/app/components/OnboardingModal/SubTopicsStep.tsx
  apps/launchpad/app/components/OnboardingModal/SummaryStep.tsx
  apps/launchpad/app/components/OnboardingModal/TopicsStep.tsx
  apps/launchpad/app/components/OnboardingModal/constants.ts
  apps/launchpad/app/components/OnboardingModal/types.ts
  apps/launchpad/app/routes/_app+/dashboard.tsx
  apps/launchpad/package.json
  pnpm-lock.yaml
Labels: feat

#1009 ENG-5279 feat(graphql,sdk): remove api dependencies from sdk and graphql
  packages/graphql/package.json
  packages/sdk/package.json
  packages/sdk/src/index.ts
  pnpm-lock.yaml
Labels: feat

#1013 ENG-5293 feat(launchpad,1ui,graphql): bring protocol points query into graphql and basic scaffolding of points route
  apps/launchpad/app/.server/api.ts
  apps/launchpad/app/.server/auth.ts
  apps/launchpad/app/lib/services/relics.ts
  apps/launchpad/app/lib/utils/misc.ts
  apps/launchpad/app/lib/utils/points.ts
  apps/launchpad/app/routes/_app+/network.tsx
  apps/launchpad/app/routes/_app+/points.tsx
  apps/launchpad/package.json
  packages/1ui/src/components/AggregatedMetrics/AggregatedMetrics.mdx
  packages/1ui/src/components/AggregatedMetrics/AggregatedMetrics.spec.tsx
  packages/1ui/src/components/AggregatedMetrics/AggregatedMetrics.stories.tsx
  packages/1ui/src/components/AggregatedMetrics/AggregatedMetrics.tsx
  packages/graphql/src/generated/index.ts
  packages/graphql/src/queries/points.graphql
  pnpm-lock.yaml
Labels: feat

#1016 ENG-0000 fix(portal): add quest set cards back to quest route
  apps/portal/app/routes/app+/quest+/index.tsx
Labels: fix

#1017 ENG-5345 feat(launchpad): troubleshoot knowledge graph build issue
  apps/launchpad/vite.config.ts
Labels: feat

#1019 ENG-5377 feat(protocol): Add protocol package versioning
  packages/protocol/README.md
  packages/protocol/package.json
  packages/protocol/src/deployments.ts
  packages/protocol/src/multivault.ts
  packages/protocol/tests/multivault.test.ts
  packages/protocol/tsup.config.ts
  pnpm-lock.yaml
Labels: feat

#1023 ENG-5353 ENG-5362 feat(launchpad): v0 scaffolding rewards route and mid-fi implementation
  apps/launchpad/app/components/AppSidebar.tsx
  apps/launchpad/app/components/aggregate-iq.tsx
  apps/launchpad/app/components/chart.tsx
  apps/launchpad/app/components/skill-modal.tsx
  apps/launchpad/app/components/skill-radar-chart.tsx
  apps/launchpad/app/data/mock-rewards.ts
  apps/launchpad/app/routes/_app+/rewards.tsx
  apps/launchpad/app/routes/_index.tsx
  apps/launchpad/app/types/rewards.ts
Labels: feat

#1020 ENG-5360 feat(launchpad): Add Leaderboard mid-fi
  apps/launchpad/app/components/AppSidebar.tsx
  apps/launchpad/app/components/layouts/types.ts
  apps/launchpad/app/components/ui/Tabs.tsx
  apps/launchpad/app/data/mock-leaderboard.ts
  apps/launchpad/app/routes/_app+/leaderboard.tsx
  apps/launchpad/app/types/leaderboard.ts
  apps/launchpad/package.json
  pnpm-lock.yaml
Labels: feat

#1022 ENG-5376 feat(graphql): update constants.ts with new testnet deployment url
  packages/graphql/package.json
  packages/graphql/src/client.ts
  packages/graphql/src/constants.ts
Labels: feat

#1025 ENG-5366 chore(launchpad): updates file casing
  apps/launchpad/app/components/activity-feed.tsx
  apps/launchpad/app/components/app-sidebar.tsx
  apps/launchpad/app/components/chapter-progress-bar.tsx
  apps/launchpad/app/components/chapter-progress.tsx
  apps/launchpad/app/components/error-page.tsx
  apps/launchpad/app/components/file-explorer-sidebar.tsx
  apps/launchpad/app/components/knowledge-graph/knowledge-graph.tsx
  apps/launchpad/app/components/layouts/app-shell-context.tsx
  apps/launchpad/app/components/layouts/app-shell.tsx
  apps/launchpad/app/components/layouts/dashboard-layout.tsx
  apps/launchpad/app/components/level-progress.tsx
  apps/launchpad/app/components/onboarding-modal/constants.ts
  apps/launchpad/app/components/onboarding-modal/intro-step.tsx
  apps/launchpad/app/components/onboarding-modal/onboarding-modal.tsx
  apps/launchpad/app/components/onboarding-modal/subtopics-step.tsx
  apps/launchpad/app/components/onboarding-modal/summary-step.tsx
  apps/launchpad/app/components/onboarding-modal/topics-step.tsx
  apps/launchpad/app/components/onboarding-modal/types.ts
  apps/launchpad/app/components/portfolio-stats.tsx
  apps/launchpad/app/components/time-filter.tsx
  apps/launchpad/app/data/mock-leaderboard.ts
  apps/launchpad/app/routes/_app+/dashboard.tsx
  apps/launchpad/app/routes/_app+/leaderboard.tsx
  apps/launchpad/app/routes/_app+/network.tsx
  apps/launchpad/app/routes/_app+/rewards.tsx
  apps/launchpad/app/routes/_app.tsx
  apps/launchpad/app/routes/preferences+/_layout.tsx
Labels: chore

#1024 ENG-5375 feat(launchpad): wire up basic optional auth with dynamic client side imports
  apps/launchpad/app/components/account-button.tsx
  apps/launchpad/app/components/app-sidebar.tsx
  apps/launchpad/app/components/connect-button.tsx
  apps/launchpad/app/components/loading-button.tsx
  apps/launchpad/app/components/ui/tabs.tsx
  apps/launchpad/app/lib/providers/auth-provider.tsx
  apps/launchpad/app/lib/providers/index.tsx
  apps/launchpad/app/lib/providers/privy.tsx
  apps/launchpad/app/lib/server/auth.ts
  apps/launchpad/app/lib/server/privy.ts
  apps/launchpad/app/lib/utils/misc.ts
  apps/launchpad/app/lib/utils/privy-errors.ts
  apps/launchpad/app/lib/utils/wagmi.ts
  apps/launchpad/app/root.tsx
  apps/launchpad/app/routes/_app+/points.tsx
  apps/launchpad/package.json
  apps/launchpad/vite.config.ts
  pnpm-lock.yaml
Labels: feat

#1027 ENG-5359 ENG-5361 feat(launchpad): v0 scaffolding preferences marketplace and mid-fi implementation
  apps/launchpad/app/components/app-sidebar.tsx
  apps/launchpad/app/components/preferences/add-preference-form.tsx
  apps/launchpad/app/components/preferences/preference-card.tsx
  apps/launchpad/app/components/preferences/preference-chat.tsx
  apps/launchpad/app/components/preferences/stake-eth-form.tsx
  apps/launchpad/app/data/mock-preferences.ts
  apps/launchpad/app/routes/_app+/marketplaces+/preferences.tsx
Labels: feat

#1028 ENG-5400 feat(launchpad): appsidebar, cards, and general layout fidelity pass
  apps/launchpad/app/components/account-button.tsx
  apps/launchpad/app/components/activity-feed.tsx
  apps/launchpad/app/components/aggregate-iq.tsx
  apps/launchpad/app/components/app-sidebar.tsx
  apps/launchpad/app/components/chapter-progress-bar.tsx
  apps/launchpad/app/components/chapter-progress.tsx
  apps/launchpad/app/components/layouts/app-shell.tsx
  apps/launchpad/app/components/layouts/dashboard-layout.tsx
  apps/launchpad/app/components/layouts/types.ts
  apps/launchpad/app/components/level-progress.tsx
  apps/launchpad/app/components/onboarding-modal/onboarding-modal.tsx
  apps/launchpad/app/components/onboarding-modal/subtopics-step.tsx
  apps/launchpad/app/components/onboarding-modal/summary-step.tsx
  apps/launchpad/app/components/onboarding-modal/topics-step.tsx
  apps/launchpad/app/components/portfolio-stats.tsx
  apps/launchpad/app/components/skill-modal.tsx
  apps/launchpad/app/components/time-filter.tsx
  apps/launchpad/app/root.tsx
  apps/launchpad/app/routes/_app+/dashboard.tsx
  apps/launchpad/app/routes/_app+/leaderboard.tsx
  apps/launchpad/app/routes/_app+/network.tsx
  apps/launchpad/app/routes/_app+/rewards.tsx
  apps/launchpad/app/styles/globals.css
  apps/launchpad/tailwind.config.js
  packages/1ui/src/components/PageHeader/PageHeader.tsx
  packages/1ui/src/utils/number.ts
Labels: feat

#1031 ENG-5457 feat(graphql): package parity with main
  packages/graphql/codegen.ts
  packages/graphql/package.json
  packages/graphql/src/client.ts
  packages/graphql/src/constants.ts
  pnpm-lock.yaml
Labels: feat

#1026 ENG-0000 fix(protocol): readme example and upgrade viem dep
  packages/protocol/README.md
  packages/protocol/package.json
  pnpm-lock.yaml
Labels: fix

#1033 ENG-5432 ENG-5466 feat(launchpad): detail page routing layout and appshell update with statsbar
  apps/launchpad/app/components/layouts/app-shell.tsx
  apps/launchpad/app/components/stats-bar.tsx
  apps/launchpad/app/lib/hooks/useGoBack.tsx
  apps/launchpad/app/routes/_app+/minigames+/game-1.tsx
Labels: feat

#1034 ENG-5428 ENG-5429 feat(launchpad): sharing modal flow
  apps/launchpad/app/components/share-modal.tsx
  apps/launchpad/app/lib/state/store.ts
  apps/launchpad/app/routes/_app+/minigames+/game-1.tsx
  apps/launchpad/package.json
  pnpm-lock.yaml
Labels: feat

#1036 ENG-5421 feat(launchpad): home page flow scaffolding
  apps/launchpad/app/components/auth-cover.tsx
  apps/launchpad/app/components/minigame-card-wrapper.tsx
  apps/launchpad/app/components/minigame-card.tsx
  apps/launchpad/app/components/onboarding-modal/constants.ts
  apps/launchpad/app/components/onboarding-modal/onboarding-modal.tsx
  apps/launchpad/app/components/onboarding-modal/topics-step.tsx
  apps/launchpad/app/lib/data/mock-minigames.ts
  apps/launchpad/app/lib/hooks/useMinigameData.ts
  apps/launchpad/app/lib/state/store.ts
  apps/launchpad/app/lib/types/minigame.ts
  apps/launchpad/app/routes/_app+/dashboard.tsx
  apps/launchpad/app/routes/_app+/minigames+/game-1.tsx
Labels: feat

#1035 ENG-5452 feat(launchpad,1ui,graphql): add ability to create new atom
  apps/launchpad/app/.server/cloudinary.ts
  apps/launchpad/app/components/atom-forms/atom-type-select.tsx
  apps/launchpad/app/components/atom-forms/create-toast.tsx
  apps/launchpad/app/components/atom-forms/form-container.tsx
  apps/launchpad/app/components/atom-forms/form-fields/eth-input.tsx
  apps/launchpad/app/components/atom-forms/form-fields/image-upload.tsx
  apps/launchpad/app/components/atom-forms/form-fields/index.ts
  apps/launchpad/app/components/atom-forms/form-fields/input.tsx
  apps/launchpad/app/components/atom-forms/form-fields/textarea.tsx
  apps/launchpad/app/components/atom-forms/forms/deposit-form.tsx
  apps/launchpad/app/components/atom-forms/forms/index.ts
  apps/launchpad/app/components/atom-forms/forms/organization-form.tsx
  apps/launchpad/app/components/atom-forms/forms/person-form.tsx
  apps/launchpad/app/components/atom-forms/forms/thing-form.tsx
  apps/launchpad/app/components/atom-forms/index.ts
  apps/launchpad/app/components/atom-forms/registry.ts
  apps/launchpad/app/components/atom-forms/step-indicator.tsx
  apps/launchpad/app/components/atom-forms/types.ts
  apps/launchpad/app/components/create-atom-modal.tsx
  apps/launchpad/app/components/loading-logo.tsx
  apps/launchpad/app/components/onboarding-modal/constants.ts
  apps/launchpad/app/components/onboarding-modal/onboarding-modal.tsx
  apps/launchpad/app/components/onboarding-modal/topics-step.tsx
  apps/launchpad/app/components/onboarding-modal/types.ts
  apps/launchpad/app/components/search.tsx
  apps/launchpad/app/components/step.tsx
  apps/launchpad/app/components/transaction-state.tsx
  apps/launchpad/app/consts/general.ts
  apps/launchpad/app/lib/hooks/mutations/useCreateMutation.tsx
  apps/launchpad/app/lib/hooks/useAtomCost.tsx
  apps/launchpad/app/lib/hooks/useCreateAtomConfig.tsx
  apps/launchpad/app/lib/hooks/useCreateTripleConfig.tsx
  apps/launchpad/app/lib/hooks/useDebounce.tsx
  apps/launchpad/app/lib/hooks/useTransactionReducer copy.ts
  apps/launchpad/app/lib/utils/app.ts
  apps/launchpad/app/routes/actions+/upload-image.ts
  apps/launchpad/app/routes/resources+/create-triple.tsx
  apps/launchpad/app/routes/resources+/create.tsx
  apps/launchpad/package.json
  apps/launchpad/vite.config.ts
  packages/1ui/package.json
  packages/1ui/src/components/Form/Form.mdx
  packages/1ui/src/components/Form/Form.spec.tsx
  packages/1ui/src/components/Form/Form.stories.tsx
  packages/1ui/src/components/Form/Form.tsx
  packages/1ui/src/components/Form/index.ts
  packages/1ui/src/components/index.tsx
  packages/graphql/src/generated/index.ts
  packages/graphql/src/mutations/pin-thing.graphql
  packages/graphql/src/queries/atoms.graphql
  pnpm-lock.yaml
Labels: feat

#1038 ENG-5470 ENG-5459 feat(launchpad): add list sharing modal, update navbar and stats bar
  apps/launchpad/app/components/app-sidebar.tsx
  apps/launchpad/app/components/share-modal.tsx
  apps/launchpad/app/components/stats-bar.tsx
Labels: feat

#1039 ENG-5433 ENG-5473 feat(launchpad): tcr table list with results, adds ctas to each page
  apps/launchpad/app/components/layouts/app-shell-context.tsx
  apps/launchpad/app/components/layouts/app-shell.tsx
  apps/launchpad/app/components/layouts/types.ts
  apps/launchpad/app/components/minigame-card.tsx
  apps/launchpad/app/components/onboarding-modal/onboarding-modal.tsx
  apps/launchpad/app/components/ui/table/columns.tsx
  apps/launchpad/app/components/ui/table/data-table-column-header.tsx
  apps/launchpad/app/components/ui/table/data-table-pagination.tsx
  apps/launchpad/app/components/ui/table/data-table-row-actions.tsx
  apps/launchpad/app/components/ui/table/data-table-toolbar.tsx
  apps/launchpad/app/components/ui/table/data-table-view-options.tsx
  apps/launchpad/app/components/ui/table/data-table.tsx
  apps/launchpad/app/routes/_app+/minigames+/game-1.tsx
  apps/launchpad/package.json
  pnpm-lock.yaml
Labels: feat

#1042 ENG-5463 feat(launchpad): detail modal table row click
  apps/launchpad/app/components/atom-details-card.tsx
  apps/launchpad/app/components/atom-details-modal.tsx
  apps/launchpad/app/components/ui/table/columns.tsx
  apps/launchpad/app/components/ui/table/data-table.tsx
  apps/launchpad/app/lib/state/store.ts
  apps/launchpad/app/routes/_app+/minigames+/game-1.tsx
Labels: feat

#1043 ENG-5479 feat(launchpad,1ui): create simple creation form specifically for minigames
  apps/launchpad/app/components/atom-forms/forms/survey-deposit-form.tsx
  apps/launchpad/app/components/atom-forms/survey-form-container.tsx
  apps/launchpad/app/components/loading-logo.tsx
  apps/launchpad/app/components/onboarding-modal/create-step.tsx
  apps/launchpad/app/components/onboarding-modal/onboarding-modal.tsx
  apps/launchpad/app/components/onboarding-modal/stake-step.tsx
  apps/launchpad/app/components/onboarding-modal/topics-step.tsx
  apps/launchpad/app/components/onboarding-modal/types.ts
  apps/launchpad/app/components/transaction-state.tsx
  packages/1ui/src/components/StepIndicator/Step.tsx
  packages/1ui/src/components/StepIndicator/StepIndicator.tsx
Labels: title needs formatting, feat

#1045 ENG-5478 feat(launchpad,1ui): adjust the aggregatedmetrics component to allow optional precision
  apps/launchpad/app/routes/_app+/minigames+/game-1.tsx
  apps/launchpad/app/routes/_app+/network.tsx
  packages/1ui/src/components/AggregatedMetrics/AggregatedMetrics.spec.tsx
  packages/1ui/src/components/AggregatedMetrics/AggregatedMetrics.tsx
Labels: feat

#1046 ENG-5494 feat(launchpad): add tooltiplink to docs on staking flow
  apps/launchpad/app/components/atom-forms/forms/survey-deposit-form.tsx
  apps/launchpad/app/components/atom-forms/survey-form-container.tsx
  apps/launchpad/app/components/onboarding-modal/onboarding-modal.tsx
  apps/launchpad/app/components/onboarding-modal/signal-step.tsx
  apps/launchpad/app/components/onboarding-modal/signal-toast.tsx
  apps/launchpad/app/components/onboarding-modal/topics-step.tsx
  apps/launchpad/app/components/onboarding-modal/types.ts
Labels: feat

#1047 ENG-5469 feat(launchpad): wire up points to home page and success handler
  apps/launchpad/app/components/minigame-card-wrapper.tsx
  apps/launchpad/app/components/minigame-card.tsx
  apps/launchpad/app/components/onboarding-modal/onboarding-modal.tsx
  apps/launchpad/app/components/onboarding-modal/reward-step.tsx
  apps/launchpad/app/lib/hooks/usePoints.ts
  apps/launchpad/app/routes/actions+/reward-points.ts
  apps/launchpad/app/routes/resources+/get-points.ts
  apps/launchpad/package.json
  pnpm-lock.yaml
Labels: feat

#1048 ENG-5505 ENG-5506 feat(launchpad): add more cards upcoming games, loading logo, and improves react query caching
  apps/launchpad/app/components/app-sidebar.tsx
  apps/launchpad/app/components/loading-logo.tsx
  apps/launchpad/app/components/minigame-card-wrapper.tsx
  apps/launchpad/app/components/onboarding-modal/topics-step.tsx
  apps/launchpad/app/lib/hooks/useMinigameData.ts
  apps/launchpad/app/routes/_app+/dashboard.tsx
Labels: feat

#1050 ENG-5514 fix(launchpad): fix build deploy issue
  apps/launchpad/app/routes/resources+/get-points.ts
Labels: fix

#1051 ENG-5550 feat(launchpad): initial cleanup pass
  apps/launchpad/app/components/atom-forms/form-fields/image-upload.tsx
  apps/launchpad/app/components/atom-forms/forms/deposit-form.tsx
  apps/launchpad/app/components/atom-forms/forms/survey-deposit-form.tsx
  apps/launchpad/app/components/create-atom-modal.tsx
  apps/launchpad/app/components/knowledge-graph/knowledge-graph.tsx
  apps/launchpad/app/components/layouts/app-shell.tsx
  apps/launchpad/app/components/onboarding-modal/create-step.tsx
  apps/launchpad/app/components/onboarding-modal/onboarding-modal.tsx
  apps/launchpad/app/components/onboarding-modal/signal-step.tsx
  apps/launchpad/app/routes/_app+/network.tsx
  apps/launchpad/app/routes/actions+/reward-points.ts
Labels: feat

#1052 ENG-5540 feat(launchpad): ux first pass
  apps/launchpad/app/components/app-sidebar.tsx
  apps/launchpad/app/components/minigame-card-wrapper.tsx
  apps/launchpad/app/components/minigame-card.tsx
  apps/launchpad/app/components/quest-card.tsx
  apps/launchpad/app/components/quests-card.tsx
  apps/launchpad/app/lib/data/mock-minigames.ts
  apps/launchpad/app/lib/types/minigame.ts
  apps/launchpad/app/routes/_app+/quests+/index.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/index.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/question+/$id.tsx
Labels: feat

#1053 ENG-5556 feat(launchpad): ux second pass
  apps/launchpad/app/components/auth-cover.tsx
  apps/launchpad/app/components/layouts/app-shell.tsx
  apps/launchpad/app/components/onboarding-modal/onboarding-modal.tsx
  apps/launchpad/app/components/onboarding-modal/topics-step.tsx
  apps/launchpad/app/lib/hooks/usePoints.ts
  apps/launchpad/app/lib/utils/constants.ts
  apps/launchpad/app/routes/_app+/quests+/index.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/question+/$id.tsx
  apps/launchpad/app/styles/globals.css
Labels: feat

#1055 ENG-5521 feat(launchpad): optimize prefetching strategy
  apps/launchpad/app/.server/multivault.ts
  apps/launchpad/app/components/onboarding-modal/onboarding-modal.tsx
  apps/launchpad/app/components/onboarding-modal/reward-step.tsx
  apps/launchpad/app/components/onboarding-modal/signal-step.tsx
  apps/launchpad/app/consts/general.ts
  apps/launchpad/app/lib/hooks/useGetMultiVaultConfig.tsx
  apps/launchpad/app/routes/_app.tsx
  apps/launchpad/app/routes/actions+/reward-points.ts
  apps/launchpad/app/routes/resources+/get-vault-config.tsx
  apps/launchpad/app/types/vault.ts
Labels: feat

#1056 ENG-5566 feat(launchpad): manage chain switching
  apps/launchpad/app/components/onboarding-modal/signal-step.tsx
  apps/launchpad/app/components/submit-button.tsx
Labels: feat

#1057 ENG-5574 feat(launchpad): wire up questions graphql query
  apps/launchpad/app/components/minigame-card-wrapper.tsx
  apps/launchpad/app/components/onboarding-modal/topics-step.tsx
  apps/launchpad/app/lib/graphql/client.ts
  apps/launchpad/app/lib/graphql/types.ts
  apps/launchpad/app/lib/hooks/useQuestionData.ts
  apps/launchpad/app/routes/_app+/dashboard.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/index.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/question+/$id.tsx
  apps/launchpad/app/routes/resources+/get-points.ts
  apps/launchpad/app/routes/resources+/get-questions.$id.ts
  apps/launchpad/app/routes/resources+/get-questions.ts
Labels: feat

#1058 ENG-5565 feat(launchpad): manage api url providers environment
  apps/launchpad/app/components/onboarding-modal/onboarding-modal.tsx
  apps/launchpad/app/lib/hooks/useQuestionData.ts
  apps/launchpad/app/lib/providers/index.tsx
  apps/launchpad/app/root.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/question+/$id.tsx
Labels: feat

#1059 ENG-5430 feat(launchpad): satori social share
  apps/launchpad/app/.server/og.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/question+/$id.tsx
  apps/launchpad/app/routes/resources+/create-og.ts
  apps/launchpad/package.json
  pnpm-lock.yaml
Labels: feat

#1060 ENG-5587 feat(launchpad): logout privy if no wallet connected
  apps/launchpad/app/.client/privy-logout.tsx
  apps/launchpad/app/.server/auth.ts
  apps/launchpad/app/components/onboarding-modal/signal-step.tsx
  apps/launchpad/app/lib/utils/misc.tsx
  apps/launchpad/app/routes/_app.tsx
  apps/launchpad/app/routes/actions+/logout.tsx
Labels: feat

#1061 ENG-5590 fix(launchpad): atom creation fails
  apps/launchpad/app/components/atom-forms/forms/survey-deposit-form.tsx
  apps/launchpad/app/components/submit-button.tsx
Labels: fix

#1062 ENG-5588 fix(launchpad): keep the modal open until they close it
  apps/launchpad/app/components/onboarding-modal/onboarding-modal.tsx
Labels: fix

#1066 ENG-5594 fix(launchpad): fix validation errors in create step
  apps/launchpad/app/components/atom-forms/forms/deposit-form.tsx
  apps/launchpad/app/components/atom-forms/forms/survey-deposit-form.tsx
  apps/launchpad/app/components/atom-forms/types.ts
  apps/launchpad/app/components/onboarding-modal/create-step.tsx
Labels: fix

#1068 ENG-5608 feat(launchpad): bump privy packages and change auth approach
  apps/launchpad/app/.server/auth.ts
  apps/launchpad/app/.server/privy.ts
  apps/launchpad/app/lib/providers/auth-provider.tsx
  apps/launchpad/package.json
  pnpm-lock.yaml
Labels: feat

#1070 ENG-5623 feat(graphql): graphql codegen change to be more flexible
  packages/graphql/codegen.ts
  packages/graphql/schema.graphql
  packages/graphql/src/generated/index.ts
Labels: feat

#1072 ENG-5614 feat(launchpad): streamline account dropdown menu
  apps/launchpad/app/components/account-button.tsx
Labels: feat

#1073 ENG-5611 feat(launchpad): change icon field structure and update external links in app sidebar
  apps/launchpad/app/components/app-sidebar.tsx
Labels: feat

#1076 ENG-0000 feat(repo): merge feature/launchpad-dev into feature/launchpad
  apps/launchpad/app/components/account-button.tsx
  apps/launchpad/app/components/app-sidebar.tsx
  apps/launchpad/app/components/minigame-card-wrapper.tsx
  apps/launchpad/app/components/minigame-card.tsx
  apps/launchpad/app/components/ui/table/columns.tsx
  apps/launchpad/app/components/ui/table/data-table-pagination.tsx
  apps/launchpad/app/components/ui/table/data-table.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/question+/$id.tsx
  apps/launchpad/app/routes/_index.tsx
  packages/graphql/codegen.ts
  packages/graphql/schema.graphql
  packages/graphql/src/generated/index.ts
Labels: feat

#1077 ENG-5661 fix(launchpad): troubleshoot environment handling
  apps/launchpad/Dockerfile
  apps/launchpad/app/.server/env.ts
  apps/launchpad/app/root.tsx
  render.yaml
Labels: fix

#1080 ENG-5675 feat(launchpad): qa pass fixes
  apps/launchpad/app/components/app-sidebar.tsx
  apps/launchpad/app/lib/utils/constants.ts
Labels: feat

#1079 ENG-5664 feat(launchpad,portal,graphql): bring signaling closer to portal state
  apps/launchpad/app/.server/multivault.ts
  apps/launchpad/app/components/atom-details-card.tsx
  apps/launchpad/app/components/atom-details-modal.tsx
  apps/launchpad/app/components/atom-forms/forms/survey-deposit-form.tsx
  apps/launchpad/app/components/create-atom-modal.tsx
  apps/launchpad/app/components/error-list.tsx
  apps/launchpad/app/components/info-tooltip.tsx
  apps/launchpad/app/components/share-modal.tsx
  apps/launchpad/app/components/signal-modal/signal-button.tsx
  apps/launchpad/app/components/signal-modal/signal-modal.tsx
  apps/launchpad/app/components/signal-modal/signal-step.tsx
  apps/launchpad/app/components/signal-modal/types.ts
  apps/launchpad/app/components/signal/signal-actions.tsx
  apps/launchpad/app/components/signal/signal-button.tsx
  apps/launchpad/app/components/signal/signal-fee-breakdown.tsx
  apps/launchpad/app/components/signal/signal-form.tsx
  apps/launchpad/app/components/signal/signal-input.tsx
  apps/launchpad/app/components/signal/signal-modal.tsx
  apps/launchpad/app/components/signal/signal-review.tsx
  apps/launchpad/app/components/signal/signal-toast.tsx
  apps/launchpad/app/components/survey-modal/constants.ts
  apps/launchpad/app/components/survey-modal/create-step.tsx
  apps/launchpad/app/components/survey-modal/intro-step.tsx
  apps/launchpad/app/components/survey-modal/reward-step.tsx
  apps/launchpad/app/components/survey-modal/signal-step.tsx
  apps/launchpad/app/components/survey-modal/signal-toast.tsx
  apps/launchpad/app/components/survey-modal/survey-modal.tsx
  apps/launchpad/app/components/survey-modal/topics-step.tsx
  apps/launchpad/app/components/survey-modal/types.ts
  apps/launchpad/app/components/ui/table/columns.tsx
  apps/launchpad/app/components/ui/table/data-table.tsx
  apps/launchpad/app/lib/hooks/mutations/useStakeMutation.tsx
  apps/launchpad/app/lib/state/store.ts
  apps/launchpad/app/lib/utils/helpers.ts
  apps/launchpad/app/routes/_app+/dashboard.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/index.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/question+/$id.tsx
  apps/launchpad/app/routes/_app.tsx
  apps/launchpad/app/styles/globals.css
  apps/launchpad/app/types/atom.ts
  apps/launchpad/app/types/index.ts
  apps/launchpad/app/types/triple.ts
  apps/launchpad/app/types/vault.ts
  apps/portal/app/routes/app+/list+/$id+/index.tsx
  apps/portal/app/routes/app+/quest+/chapter+/1-6-always_true.tsx
  apps/portal/app/routes/readonly+/list+/$id+/index.tsx
  packages/graphql/src/generated/index.ts
  packages/graphql/src/queries/lists.graphql
Labels: feat

#1081 ENG-5676 feat(launchpad): critical qa pass
  apps/launchpad/app/components/activity-feed.tsx
  apps/launchpad/app/routes/_app+/network.tsx
Labels: feat

#1083 ENG-5678 fix(launchpad): hide image upload from create form temporarily
  apps/launchpad/app/components/atom-forms/forms/thing-form.tsx
Labels: fix

#1086 ENG-5682 feat(launchpad): temporarily removes network page
  apps/launchpad/app/components/app-sidebar.tsx
Labels: feat

#1087 ENG-0000 feat(repo): merge feature/launchpad-dev into feature/launchpad
  apps/launchpad/app/.server/multivault.ts
  apps/launchpad/app/components/activity-feed.tsx
  apps/launchpad/app/components/app-sidebar.tsx
  apps/launchpad/app/components/atom-details-card.tsx
  apps/launchpad/app/components/atom-details-modal.tsx
  apps/launchpad/app/components/atom-forms/forms/survey-deposit-form.tsx
  apps/launchpad/app/components/atom-forms/forms/thing-form.tsx
  apps/launchpad/app/components/create-atom-modal.tsx
  apps/launchpad/app/components/error-list.tsx
  apps/launchpad/app/components/info-tooltip.tsx
  apps/launchpad/app/components/share-modal.tsx
  apps/launchpad/app/components/signal-modal/signal-button.tsx
  apps/launchpad/app/components/signal-modal/signal-modal.tsx
  apps/launchpad/app/components/signal-modal/signal-step.tsx
  apps/launchpad/app/components/signal-modal/types.ts
  apps/launchpad/app/components/signal/signal-actions.tsx
  apps/launchpad/app/components/signal/signal-button.tsx
  apps/launchpad/app/components/signal/signal-fee-breakdown.tsx
  apps/launchpad/app/components/signal/signal-form.tsx
  apps/launchpad/app/components/signal/signal-input.tsx
  apps/launchpad/app/components/signal/signal-modal.tsx
  apps/launchpad/app/components/signal/signal-review.tsx
  apps/launchpad/app/components/signal/signal-toast.tsx
  apps/launchpad/app/components/survey-modal/constants.ts
  apps/launchpad/app/components/survey-modal/create-step.tsx
  apps/launchpad/app/components/survey-modal/intro-step.tsx
  apps/launchpad/app/components/survey-modal/reward-step.tsx
  apps/launchpad/app/components/survey-modal/signal-step.tsx
  apps/launchpad/app/components/survey-modal/signal-toast.tsx
  apps/launchpad/app/components/survey-modal/survey-modal.tsx
  apps/launchpad/app/components/survey-modal/topics-step.tsx
  apps/launchpad/app/components/survey-modal/types.ts
  apps/launchpad/app/components/ui/table/columns.tsx
  apps/launchpad/app/components/ui/table/data-table.tsx
  apps/launchpad/app/lib/hooks/mutations/useStakeMutation.tsx
  apps/launchpad/app/lib/state/store.ts
  apps/launchpad/app/lib/utils/constants.ts
  apps/launchpad/app/lib/utils/helpers.ts
  apps/launchpad/app/routes/_app+/dashboard.tsx
  apps/launchpad/app/routes/_app+/network.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/index.tsx
  apps/launchpad/app/routes/_app+/quests+/questions+/question+/$id.tsx
  apps/launchpad/app/routes/_app.tsx
  apps/launchpad/app/styles/globals.css
  apps/launchpad/app/types/atom.ts
  apps/launchpad/app/types/index.ts
  apps/launchpad/app/types/triple.ts
  apps/launchpad/app/types/vault.ts
  apps/portal/app/routes/app+/list+/$id+/index.tsx
  apps/portal/app/routes/app+/quest+/chapter+/1-6-always_true.tsx
  apps/portal/app/routes/readonly+/list+/$id+/index.tsx
  packages/graphql/src/generated/index.ts
  packages/graphql/src/queries/lists.graphql
Labels: feat

#1088 ENG-5688 fix(launchpad): fix list with position queries on results page
  apps/launchpad/app/components/signal-modal/signal-button.tsx
  apps/launchpad/app/components/ui/table/columns.tsx
  apps/launchpad/app/consts/general.ts
  apps/launchpad/app/routes/_app+/quests+/questions+/question+/$id.tsx
Labels: fix

#1089 ENG-0000 feat(repo): merge feature/launchpad-dev into feature/launchpad
  apps/launchpad/app/components/signal-modal/signal-button.tsx
  apps/launchpad/app/components/ui/table/columns.tsx
  apps/launchpad/app/consts/general.ts
  apps/launchpad/app/routes/_app+/quests+/questions+/question+/$id.tsx
Labels: feat
